import { CHARACTERS, STAGES } from '../data/meta';
import { SaveSystem } from '../systems/save';
import { UPGRADES } from '../data/upgrades';
import { createCampaignGunDefs } from '../systems/gun-loadout';
import { drawGunArt, drawHunterPortrait } from '../graphics/campaign-menu-art';
import { UI_PALETTE as C } from './palette';
import { createQuarantineBackdrop } from './horror-texture';
import { getStageCopy, getUiTerm, localizeZombieName, sentenceCaseDisplay } from '../data/localization';

export type CampaignPage = 'character' | 'stages' | 'briefing' | 'armory' | 'result' | 'failure';
type Button = { x: number; y: number; w: number; h: number; label: string; action: string; disabled?: boolean; selected?: boolean };
export type CampaignResult = {
  time: number;
  kills: number;
  reward: number;
  newStage: number;
  optional: number;
  score: number;
  scoreAdded: number;
  previousTotalScore: number;
  totalScore: number;
};
const GUNS = createCampaignGunDefs();
const DRONE_UPGRADE = UPGRADES.find(def => def.id === 'drone')!;
const GUN_AMMO_COST: Record<string, number> = {
  ar7: 32, smg9: 38, sg12: 42, dmr55: 58, bulldog: 55,
  lmg6: 68, flamer8: 65, rpg4: 82, rail_lance: 90,
};
const GUN_UPGRADE_COSTS = [100, 250, 450];

function savedAmmo(p: SaveSystem['data']['campaign'], gunId: string): { currentAmmo: number; reserveAmmo: number } {
  const saved = p.gunAmmo[gunId];
  if (saved) return saved;
  const gun = GUNS.find(value => value.id === gunId)!;
  if (gunId === 'p9') return { currentAmmo: gun.magSize, reserveAmmo: -1 };
  return { currentAmmo: gun.magSize, reserveAmmo: p.ownedGuns.includes(gunId)
    ? gun.magSize * (gun.reserveMagazines ?? 5) : 0 };
}

/** Canvas campaign front-end. Buttons and hitboxes are generated by the same draw pass. */
export class CampaignUI {
  page: CampaignPage = 'character';
  selectedStage = 0;
  stagePage = 0;
  result: CampaignResult = { time: 0, kills: 0, reward: 0, newStage: 0, optional: 0,
    score: 0, scoreAdded: 0, previousTotalScore: 0, totalScore: 0 };
  message = '';
  armoryTab: 'guns' | 'drone' = 'guns';
  gunPage = 0;
  selectedGunId = '';
  private gunListNeedsSync = true;
  focusedCharacter = 'survivor';
  canWatchRevive = true;
  reviveAdAvailable = false;
  reviveAdPending = false;
  impossibleDeath = false;
  private buttons: Button[] = [];
  private backdrop?: HTMLCanvasElement;
  private backdropLanguage?: 'vi' | 'en';
  private resultAnimationStartedAt = 0;
  private language: 'vi' | 'en' = 'vi';

  showResult(result: CampaignResult): void {
    this.result = result;
    this.resultAnimationStartedAt = performance.now();
  }

  click(x: number, y: number, save: SaveSystem): string | null {
    this.language = save.data.language;
    if (this.page === 'failure' && this.reviveAdPending) return null;
    const b = this.buttons.findLast(v => x >= v.x && x <= v.x + v.w && y >= v.y && y <= v.y + v.h);
    if (!b || b.disabled) return null;
    const p = save.data.campaign;
    this.message = '';
    if (b.action === 'back') {
      this.page = this.page === 'character' ? 'character' : this.page === 'armory' ? 'character' : this.page === 'stages' ? 'armory' : 'stages';
      return this.page === 'character' && b.label.includes('MENU') ? 'main' : null;
    }
    if (b.action === 'main') return 'main';
    if (b.action === 'stages') { this.page = 'stages'; return null; }
    if (b.action === 'briefing') { this.page = 'briefing'; return null; }
    if (b.action === 'armory') { this.page = 'armory'; this.prepareGunShowcase(p.equippedGun); return null; }
    if (b.action === 'post_stage_armory') {
      this.page = 'armory';
      this.armoryTab = 'guns';
      this.prepareGunShowcase(p.equippedGun);
      return null;
    }
    if (b.action === 'tab:guns' || b.action === 'tab:drone') { this.armoryTab = b.action === 'tab:guns' ? 'guns' : 'drone'; return null; }
    if (b.action.startsWith('gunpage:')) { this.gunPage = Number(b.action.slice(8)); return null; }
    if (b.action.startsWith('focus:')) { this.focusedCharacter = b.action.slice(6); return null; }
    if (b.action === 'drone') {
      const level = p.cardLevels.drone ?? 0;
      if (level >= DRONE_UPGRADE.maxLevel) return null;
      const cost = this.dronePrice(level);
      if (!save.spendCampaign(cost)) { this.message = this.language === 'en' ? 'Not enough credits' : 'Không đủ tín dụng'; return null; }
      p.cardLevels.drone = level + 1; save.save(); this.message = this.language === 'en' ? `Drone upgraded · level ${level + 1}` : `Đã nâng drone · cấp ${level + 1}`; return null;
    }
    if (b.action === 'start') return 'start';
    if (b.action === 'retry') return 'retry';
    if (b.action === 'revive_ad') return 'revive_ad';
    if (b.action === 'return_armory') { this.page = 'armory'; this.prepareGunShowcase(p.equippedGun); return null; }
    if (b.action === 'next') {
      this.selectedStage = Math.min(STAGES.length - 1, this.selectedStage + 1);
      this.page = 'briefing'; return null;
    }
    if (b.action.startsWith('page:')) { this.stagePage = Number(b.action.slice(5)); return null; }
    if (b.action.startsWith('focusgun:')) {
      this.armoryTab = 'guns';
      this.selectedGunId = b.action.slice(9);
      this.gunListNeedsSync = true;
      return null;
    }
    if (b.action === 'focusdrone') { this.armoryTab = 'drone'; this.gunListNeedsSync = true; return null; }
    if (b.action.startsWith('stage:')) {
      const index = Number(b.action.slice(6));
      if (index + 1 <= p.unlockedStage) { this.selectedStage = index; this.page = 'briefing'; }
      return null;
    }
    if (b.action.startsWith('char:')) {
      const id = b.action.slice(5);
      const c = CHARACTERS.find(v => v.id === id);
      if (!c) return null;
      this.focusedCharacter = id;
      if (!p.unlockedCharacters.includes(id)) {
        p.unlockedCharacters.push(id);
      }
      p.selectedCharacter = id; save.save(); return null;
    }
    if (b.action.startsWith('gun:')) {
      const id = b.action.slice(4);
      this.selectedGunId = id;
      const definition = GUNS.find(g => g.id === id);
      if (!definition || !p.ownedGuns.includes(id)) { this.message = this.language === 'en' ? 'Defeat the boss and recover this weapon first.' : 'Hãy hạ trùm và nhặt khẩu súng này trước.'; return null; }
      p.equippedGun = id; save.save(); return null;
    }
    if (b.action.startsWith('upgrade:')) {
      const id = b.action.slice(8), level = p.gunLevels[id] ?? 0;
      if (level >= 3 || !p.ownedGuns.includes(id)) return null;
      const cost = this.gunUpgradeCost(level);
      if (!save.spendCampaign(cost)) { this.message = this.language === 'en' ? 'Not enough credits' : 'Không đủ tín dụng'; return null; }
      p.gunLevels[id] = level + 1; save.save(); this.message = this.language === 'en' ? `Weapon upgraded · level ${level + 1}` : `Đã nâng súng · cấp ${level + 1}`; return null;
    }
    if (b.action.startsWith('buyammo:')) {
      const id = b.action.slice(8), gun = GUNS.find(value => value.id === id);
      const price = GUN_AMMO_COST[id] ?? 50;
      if (!gun || id === 'p9' || !p.ownedGuns.includes(id)) return null;
      const ammo = savedAmmo(p, id), rounds = gun.magSize * 2;
      if (ammo.reserveAmmo >= gun.magSize * 12) return null;
      if (!save.spendCampaign(price)) { this.message = this.language === 'en' ? 'Not enough credits' : 'Không đủ tín dụng'; return null; }
      p.gunAmmo[id] = { ...ammo, reserveAmmo: Math.min(gun.magSize * 12, ammo.reserveAmmo + rounds) };
      save.save(); return null;
    }
    if (b.action === 'med') {
      if (p.medKits >= 5 || !save.spendCampaign(70)) { this.message = p.medKits >= 5 ? (this.language === 'en' ? 'Medical kit slots are full.' : 'Túi cứu thương đã đầy.') : (this.language === 'en' ? 'Not enough credits' : 'Không đủ tín dụng'); return null; }
      p.medKits++; save.save(); return null;
    }
    if (b.action === 'flashlight') {
      if (p.flashlightLevel >= 3) return null;
      const cost = 95 + p.flashlightLevel * 75;
      if (!save.spendCampaign(cost)) { this.message = this.language === 'en' ? 'Not enough credits' : 'Không đủ tín dụng'; return null; }
      p.flashlightLevel++; save.save(); return null;
    }
    if (b.action === 'armor') {
      if (p.armorLevel >= 3) return null;
      const cost = [150, 260, 390][p.armorLevel] ?? 390;
      if (!save.spendCampaign(cost)) { this.message = this.language === 'en' ? 'Not enough credits' : 'Không đủ tín dụng'; return null; }
      p.armorLevel++; save.save(); return null;
    }
    return null;
  }

  draw(ctx: CanvasRenderingContext2D, w: number, h: number, save: SaveSystem): void {
    this.buttons.length = 0;
    this.language = save.data.language;
    const p = save.data.campaign;
    if (!this.backdrop || this.backdrop.width !== Math.ceil(w) || this.backdrop.height !== Math.ceil(h) || this.backdropLanguage !== this.language) {
      this.backdrop = createQuarantineBackdrop(w, h, this.language);
      this.backdropLanguage = this.language;
    }
    ctx.drawImage(this.backdrop, 0, 0, w, h);
    ctx.fillStyle = 'rgba(4, 7, 9, 0.32)'; ctx.fillRect(0, 0, w, h);
    const panelW = Math.min(980, w - 20), panelH = Math.min(760, h - 20);
    const x = (w - panelW) / 2, y = (h - panelH) / 2;
    const narrow = panelW < 600;
    ctx.fillStyle = C.background; ctx.fillRect(x, y, panelW, panelH);
    ctx.strokeStyle = C.border; ctx.lineWidth = 2; ctx.strokeRect(x, y, panelW, panelH);
    ctx.fillStyle = C.textSoft; ctx.textAlign = 'left'; ctx.font = 'bold 15px Segoe UI, Arial';
    const pageName = this.pageLabel();
    ctx.fillText(`${getUiTerm('campaign', this.language)} / ${pageName}`, x + 20, y + 30);
    ctx.textAlign = 'right'; ctx.fillStyle = C.amberBright; ctx.fillText(`${p.credits} ${getUiTerm('credits', this.language)}`, x + panelW - 20, y + 30);
    ctx.fillStyle = C.borderSoft; ctx.fillRect(x + 20, y + 42, panelW - 40, 1);
    if (this.page === 'character') this.characters(ctx, x, y, panelW, panelH, p, narrow);
    if (this.page === 'stages') this.stages(ctx, x, y, panelW, panelH, p, narrow);
    if (this.page === 'briefing') this.briefing(ctx, x, y, panelW, panelH, narrow, p);
    if (this.page === 'armory') this.armory(ctx, x, y, panelW, panelH, p, narrow);
    if (this.page === 'result') this.results(ctx, x, y, panelW, panelH);
    if (this.page === 'failure') this.failure(ctx, x, y, panelW, panelH);
    if (this.message) { ctx.fillStyle = C.dangerBright; ctx.textAlign = 'center'; ctx.font = 'bold 13px Segoe UI, Arial'; ctx.fillText(sentenceCaseDisplay(this.message, this.language), w / 2, y + panelH - 67); }
    this.buttons.forEach(b => this.drawButton(ctx, b));
  }

  private pageLabel(): string {
    const labels = this.language === 'en'
      ? { character: 'Character', stages: 'Missions', briefing: 'Mission brief', armory: 'Armory', result: 'Report', failure: 'Mission failed' }
      : { character: 'Nhân vật', stages: 'Tuyến màn', briefing: 'Nhiệm vụ', armory: 'Kho vũ khí', result: 'Báo cáo', failure: 'Thất bại' };
    return labels[this.page];
  }

  private prepareGunShowcase(gunId: string): void {
    this.selectedGunId = GUNS.some(gun => gun.id === gunId) ? gunId : GUNS[0].id;
    this.gunPage = 0;
    this.gunListNeedsSync = true;
  }

  private characters(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, p: SaveSystem['data']['campaign'], narrow: boolean): void {
    const english = this.language === 'en';
    this.title(ctx, english ? 'Choose a character' : 'Chọn nhân vật', x + 22, y + 78);
    const portraitW = narrow ? Math.min(155, w * .38) : Math.min(285, w * .34);
    const portraitH = Math.max(145, Math.min(h - 195, narrow ? 210 : 330));
    const focused = CHARACTERS.find(c => c.id === this.focusedCharacter) ?? CHARACTERS[0];
    this.panel(ctx, x + 22, y + 98, portraitW, portraitH, focused.color);
    drawHunterPortrait(ctx, x + 30, y + 110, portraitW - 16, portraitH - 50, focused.id, focused.color);
    ctx.fillStyle = C.text; ctx.font = `bold ${narrow ? 13 : 17}px Segoe UI, Arial`; ctx.textAlign = 'center';
    ctx.fillText(this.characterName(focused.id, focused.name), x + 22 + portraitW / 2, y + 98 + portraitH - 18, portraitW - 12);
    ctx.textAlign = 'left'; ctx.fillStyle = C.textMuted; ctx.font = `bold ${narrow ? 9 : 10}px Segoe UI, Arial`;
    ctx.fillText(english ? 'Specialty' : 'Thế mạnh', x + 23, y + 120 + portraitH, portraitW);
    ctx.fillStyle = C.amberBright; ctx.font = `bold ${narrow ? 9 : 11}px Segoe UI, Arial`;
    ctx.fillText(this.characterDescription(focused.id, focused.description), x + 23, y + 139 + portraitH, portraitW);
    const listX = x + 32 + portraitW, listW = w - portraitW - 54;
    const cardH = Math.min(narrow ? 56 : 67, (h - 195) / 6 - 4);
    CHARACTERS.forEach((c, i) => {
      const bx = listX, by = y + 98 + i * (cardH + 5), cardW = listW;
      const selected = p.selectedCharacter === c.id;
      this.panel(ctx, bx, by, cardW, cardH, this.focusedCharacter === c.id ? C.amberBright : C.borderSoft);
      ctx.fillStyle = c.color; ctx.fillRect(bx + 7, by + 8, 4, cardH - 16);
      ctx.fillStyle = C.text; ctx.font = `bold ${narrow ? 11 : 15}px Segoe UI, Arial`; ctx.textAlign = 'left'; ctx.fillText(this.characterName(c.id, c.name), bx + 18, by + 19, cardW - 95);
      if (cardH >= 45) { ctx.fillStyle = C.textSoft; ctx.font = `${narrow ? 9 : 11}px Segoe UI, Arial`; ctx.fillText(this.characterDescription(c.id, c.description), bx + 18, by + 35, cardW - 93); }
      this.add(bx + cardW - (narrow ? 74 : 108), by + 8, narrow ? 67 : 100, cardH - 16,
        selected ? (english ? 'Selected' : 'Đang chọn') : (english ? 'Choose' : 'Chọn'), `char:${c.id}`, selected);
      this.add(bx + 12, by + 2, Math.max(1, cardW - (narrow ? 90 : 125)), cardH - 4, '', `focus:${c.id}`);
    });
    this.add(x + 22, y + h - 52, Math.min(140, (w - 52) / 2), 34, english ? 'Main menu' : 'Về menu', 'main');
    this.add(x + w - Math.min(205, (w - 52) / 2) - 22, y + h - 52, Math.min(205, (w - 52) / 2), 34, english ? 'Prepare →' : 'Chuẩn bị →', 'armory');
  }

  private stages(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, p: SaveSystem['data']['campaign'], narrow: boolean): void {
    const english = this.language === 'en';
    this.title(ctx, english ? 'Campaign missions' : 'Tuyến Chiến dịch', x + 22, y + 78);
    const start = narrow ? this.stagePage * 5 : 0;
    const list = STAGES.slice(start, start + (narrow ? 5 : 10));
    const cols = narrow ? 1 : 2, gap = 8, bw = (w - 44 - gap * (cols - 1)) / cols;
    const rowH = Math.min(narrow ? 63 : 88, (h - 188) / (narrow ? 5 : 5) - gap);
    list.forEach((s, i) => {
      const bx = x + 22 + (i % cols) * (bw + gap), by = y + 95 + Math.floor(i / cols) * (rowH + gap);
      const locked = s.id > p.unlockedStage, done = p.completedStages.includes(s.id);
      this.panel(ctx, bx, by, bw, rowH, done ? '#789b88' : locked ? '#39474b' : '#bf9468');
      ctx.fillStyle = locked ? C.textMuted : C.text; ctx.textAlign = 'left'; ctx.font = `bold ${narrow ? 12 : 15}px Segoe UI, Arial`;
      const copy = getStageCopy(s, this.language);
      ctx.fillText(`${String(s.id).padStart(2, '0')}  ${copy.name}`, bx + 12, by + 25, bw - 24);
      ctx.fillStyle = C.textSoft; ctx.font = '11px Segoe UI, Arial';
      ctx.fillText(locked ? (english ? 'Locked' : 'Đã khóa') : done ? (english ? 'Complete' : 'Đã hoàn thành') :
        english ? `Unlocked · ${s.reward} credits` : `Đã mở · ${s.reward} tín dụng`, bx + 12, by + Math.min(rowH - 10, 46));
      this.add(bx, by, bw, rowH, '', `stage:${s.id - 1}`, locked);
    });
    if (narrow) { this.add(x + 22, y + h - 95, 100, 28, '01–05', 'page:0', this.stagePage === 0); this.add(x + 130, y + h - 95, 100, 28, '06–10', 'page:1', this.stagePage === 1); }
    this.add(x + 22, y + h - 52, 140, 34, english ? '← Prepare' : '← Chuẩn bị', 'back');
  }

  private briefing(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, narrow: boolean, p: SaveSystem['data']['campaign']): void {
    const s = STAGES[this.selectedStage];
    const english = this.language === 'en';
    const copy = getStageCopy(s, this.language);
    this.title(ctx, `${String(s.id).padStart(2, '0')} / ${copy.name}`, x + 22, y + 80);
    if (h < 570) {
      this.copy(ctx, english ? 'Mission' : 'Nhiệm vụ', copy.description, x + 24, y + 116, w - 48);
      this.copy(ctx, english ? 'Objective' : 'Mục tiêu', copy.objectiveLabel, x + 24, y + 190, w - 48);
      this.copy(ctx, english ? 'Target' : 'Mục tiêu', `${english ? 'Boss' : 'Trùm'}: ${copy.bossName}`, x + 24, y + 260, w - 48);
      this.add(x + 22, y + h - 52, narrow ? 112 : 150, 34, english ? '← Missions' : '← Bản đồ', 'back');
      this.add(x + w - (narrow ? 165 : 205) - 22, y + h - 52, narrow ? 165 : 205, 34, english ? 'Deploy →' : 'Vào màn →', 'start');
      return;
    }
    this.copy(ctx, english ? 'Mission' : 'Nhiệm vụ', copy.description, x + 24, y + 125, w - 48);
    this.copy(ctx, english ? 'Primary objective' : 'Mục tiêu chính', copy.objectiveLabel, x + 24, y + 205, w - 48);
    this.copy(ctx, english ? 'Field note' : 'Ghi chú hiện trường', english
      ? 'Check supply points and conserve health before the boss fight. Recover what you can along the route.'
      : 'Kiểm tra điểm tiếp tế và giữ máu trước trận trùm. Thu gom vật tư dọc đường.', x + 24, y + 285, w - 48);
    this.copy(ctx, english ? 'Threats' : 'Mối đe dọa', `${s.mobIds.map(id => this.zombieName(id)).join(' · ')}  /  ${english ? 'Boss' : 'Trùm'}: ${copy.bossName}`, x + 24, y + 365, w - 48);
    this.copy(ctx, english ? 'Field tactics' : 'Chiến thuật', english
      ? 'Ammo is limited. Walk over supply crates to collect them. Use E on mission devices, R to reload, and Shift / Space to dodge. The P-9 has unlimited reserve ammo.'
      : 'Đạn có hạn. Đi qua thùng để nhặt tiếp tế. Nhấn E dùng thiết bị nhiệm vụ, R nạp đạn, Shift / Space để lướt. P-9 có đạn dự trữ vô hạn.', x + 24, y + Math.min(445, h - 170), w - 48);
    this.add(x + 22, y + h - 52, narrow ? 112 : 150, 34, english ? '← Missions' : '← Bản đồ', 'back');
    this.add(x + w - (narrow ? 165 : 205) - 22, y + h - 52, narrow ? 165 : 205, 34, english ? 'Deploy →' : 'Vào màn →', 'start');
  }

  private armory(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, p: SaveSystem['data']['campaign'], narrow: boolean): void {
    const english = this.language === 'en';
    this.title(ctx, english ? 'Staging area' : 'Trạm chuẩn bị', x + 22, y + 77);
    this.drawGuns(ctx, x, y, w, h, p, narrow);
    this.drawGear(ctx, x, y, w, h, p, narrow);
    this.add(x + 22, y + h - 52, narrow ? 105 : 145, 34, english ? '← Character' : '← Nhân vật', 'back');
    this.add(x + w - (narrow ? 155 : 195) - 22, y + h - 52, narrow ? 155 : 195, 34, english ? 'Choose mission →' : 'Chọn màn →', 'stages');
  }

  private drawGuns(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, p: SaveSystem['data']['campaign'], narrow: boolean): void {
    const english = this.language === 'en';
    const contentX = x + 22, contentY = y + 97, contentW = w - 44;
    const contentBottom = y + h - 151;
    const areaH = Math.max(90, contentBottom - contentY);
    const compact = narrow || areaH < 360;
    if (!GUNS.some(gun => gun.id === this.selectedGunId)) {
      this.selectedGunId = GUNS.some(gun => gun.id === p.equippedGun) ? p.equippedGun : GUNS[0].id;
      this.gunListNeedsSync = true;
    }
    const droneIndex = GUNS.length;
    const selectedIndex = this.armoryTab === 'drone' ? droneIndex : Math.max(0, GUNS.findIndex(gun => gun.id === this.selectedGunId));
    const selected = GUNS[selectedIndex] ?? GUNS.find(gun => gun.id === p.equippedGun) ?? GUNS[0];
    const selectedOwned = selected.id === 'p9' || p.ownedGuns.includes(selected.id);
    const upgradeLevel = Math.min(3, p.gunLevels[selected.id] ?? 0);
    const upgradeCost = this.gunUpgradeCost(upgradeLevel);
    const damage = Math.round(selected.baseDamage * (1 + upgradeLevel * .12));
    const ammo = savedAmmo(p, selected.id);
    const reserveText = ammo.reserveAmmo < 0 ? '∞' : String(ammo.reserveAmmo);
    const contentGap = 8;
    let previewX = contentX, previewY = contentY, previewW = contentW, previewH = areaH;
    let listX = contentX, listY = contentY, listW = contentW, listH = 0;
    const railCount = GUNS.length + 1;
    let visibleRows = railCount, rowH = 0, pageCount = 1;

    if (!compact) {
      previewW = Math.round((contentW - contentGap) * .46);
      listX = contentX + previewW + contentGap;
      listW = contentW - previewW - contentGap;
      listY = contentY + 19;
      listH = Math.max(60, areaH - 19);
      rowH = listH / railCount;
      this.gunPage = 0;
      this.gunListNeedsSync = false;
    } else {
      previewH = Math.min(214, Math.max(140, areaH * .47));
      previewH = Math.min(previewH, Math.max(112, areaH - 62));
      listY = contentY + previewH + contentGap;
      listH = Math.max(38, contentBottom - listY);
      visibleRows = Math.max(1, Math.floor((listH - 27) / 40));
      pageCount = Math.ceil(railCount / visibleRows);
      if (this.gunListNeedsSync) this.gunPage = Math.floor(selectedIndex / visibleRows);
      this.gunPage = Math.max(0, Math.min(pageCount - 1, this.gunPage));
      rowH = Math.min(46, (listH - (pageCount > 1 ? 26 : 0)) / visibleRows);
      if (pageCount === 1) rowH = listH / visibleRows;
      this.gunListNeedsSync = false;
    }

    if (this.armoryTab === 'drone') {
      this.drawDroneShowcase(ctx, previewX, previewY, previewW, previewH, p, compact, english);
    } else {
      this.drawGunShowcase(ctx, previewX, previewY, previewW, previewH, selected, selectedOwned,
        p, upgradeLevel, upgradeCost, damage, ammo.currentAmmo, reserveText, compact, english);
    }

    // Keep every firearm and the hand-drawn support drone together in one equipment rail.
    const first = compact ? this.gunPage * visibleRows : 0;
    const shown = compact ? [...GUNS, null].slice(first, first + visibleRows) : [...GUNS, null];
    shown.forEach((gun, index) => {
      const by = compact ? listY + index * rowH : listY + index * rowH;
      if (!gun) {
        const isSelected = this.armoryTab === 'drone';
        this.panel(ctx, listX, by, listW, rowH - 2, isSelected ? C.cyanBright : C.borderSoft);
        ctx.fillStyle = isSelected ? 'rgba(79, 139, 145, .28)' : 'rgba(27, 37, 39, .78)';
        ctx.fillRect(listX + 1, by + 1, listW - 2, rowH - 3);
        if (isSelected) { ctx.fillStyle = C.cyanBright; ctx.fillRect(listX + 1, by + 2, 3, rowH - 5); }
        this.drawDroneIcon(ctx, listX + Math.min(43, listW * .12), by + rowH / 2, Math.min(.48, rowH / 96));
        const textX = listX + Math.min(78, listW * .23);
        ctx.fillStyle = C.text; ctx.font = `800 ${compact ? 10 : 12}px Segoe UI, Arial`;
        ctx.textAlign = 'left'; ctx.textBaseline = 'middle';
        ctx.fillText(english ? 'Support drone' : 'Drone hộ vệ', textX, by + rowH * .39, Math.max(20, listW - (textX - listX) - 78));
        ctx.fillStyle = C.textSoft; ctx.font = `600 ${compact ? 8 : 9}px Segoe UI, Arial`;
        const droneLevel = Math.min(DRONE_UPGRADE.maxLevel, p.cardLevels.drone ?? 0);
        ctx.fillText(english ? `Level ${droneLevel}/${DRONE_UPGRADE.maxLevel} · automatic fire` : `Cấp ${droneLevel}/${DRONE_UPGRADE.maxLevel} · tự động khai hỏa`, textX, by + rowH * .72,
          Math.max(20, listW - (textX - listX) - 78));
        ctx.textAlign = 'right'; ctx.fillStyle = isSelected ? C.cyanBright : C.textMuted;
        ctx.font = `800 ${compact ? 7 : 8}px Segoe UI, Arial`;
        ctx.fillText(english ? 'Support' : 'Hỗ trợ', listX + listW - 8, by + rowH / 2, 64);
        this.add(listX + 1, by + 1, listW - 2, rowH - 3, '', 'focusdrone');
        return;
      }
      const sidearm = gun.id === 'p9', owned = sidearm || p.ownedGuns.includes(gun.id);
      const equipped = p.equippedGun === gun.id;
      const isSelected = selected.id === gun.id;
      this.panel(ctx, listX, by, listW, rowH - 2, isSelected ? C.cyanBright : equipped ? C.amberBright : C.borderSoft);
      ctx.fillStyle = isSelected ? 'rgba(79, 139, 145, .28)' : equipped ? 'rgba(120, 91, 49, .22)' : 'rgba(27, 37, 39, .78)';
      ctx.fillRect(listX + 1, by + 1, listW - 2, rowH - 3);
      if (isSelected) { ctx.fillStyle = C.cyanBright; ctx.fillRect(listX + 1, by + 2, 3, rowH - 5); }
      const artW = Math.min(compact ? 82 : 100, listW * .22);
      const artH = artW * 60 / 170;
      ctx.save(); ctx.globalAlpha = owned ? 1 : .52;
      drawGunArt(ctx, listX + 8, by + Math.max(1, (rowH - 2 - artH) / 2), artW, artH, gun.id);
      ctx.restore();
      const textX = listX + artW + 18;
      const nameSize = compact ? 10 : 12;
      ctx.textAlign = 'left'; ctx.textBaseline = 'middle';
      ctx.fillStyle = owned ? C.text : C.textMuted; ctx.font = `800 ${nameSize}px Segoe UI, Arial`;
      ctx.fillText(gun.shortName, textX, by + rowH * .37, Math.max(20, listW - artW - 116));
      ctx.fillStyle = owned ? C.textSoft : C.textMuted; ctx.font = `600 ${compact ? 8 : 9}px Segoe UI, Arial`;
      const gunAmmo = savedAmmo(p, gun.id);
      ctx.fillText(owned
        ? `${english ? 'Ammo' : 'Đạn'} ${gunAmmo.currentAmmo}/${gun.magSize}  ·  ${gunAmmo.reserveAmmo < 0 ? '∞' : gunAmmo.reserveAmmo}`
        : `${english ? 'Mission' : 'Màn'} ${gun.unlockStage}  ·  ${english ? 'boss recovery' : 'hạ trùm để nhặt'}`,
      textX, by + rowH * .72, Math.max(20, listW - artW - 116));
      const status = equipped ? (english ? 'Equipped' : 'Đang dùng') : owned ? (english ? 'Owned' : 'Đã có') : (english ? 'Locked' : 'Chưa mở');
      ctx.textAlign = 'right'; ctx.fillStyle = equipped ? C.amberBright : owned ? C.cyanBright : C.textMuted;
      ctx.font = `800 ${compact ? 7 : 8}px Segoe UI, Arial`;
      ctx.fillText(status, listX + listW - 8, by + rowH / 2, 64);
      this.add(listX + 1, by + 1, listW - 2, rowH - 3, '', `focusgun:${gun.id}`);
    });

    if (compact && pageCount > 1) {
      const pagerY = listY + visibleRows * rowH + 1;
      const pageButtonW = Math.min(112, (listW - 72) / 2);
      this.add(listX, pagerY, pageButtonW, 24, english ? '← Previous' : '← Trước', `gunpage:${this.gunPage - 1}`, this.gunPage === 0);
      ctx.fillStyle = C.textSoft; ctx.textAlign = 'center'; ctx.textBaseline = 'middle'; ctx.font = '700 10px Segoe UI, Arial';
      ctx.fillText(`${this.gunPage + 1} / ${pageCount}`, listX + listW / 2, pagerY + 12);
      this.add(listX + listW - pageButtonW, pagerY, pageButtonW, 24, english ? 'Next →' : 'Sau →', `gunpage:${this.gunPage + 1}`, this.gunPage === pageCount - 1);
    }
  }

  private drawGunShowcase(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number,
    gun: typeof GUNS[number], owned: boolean, p: SaveSystem['data']['campaign'], level: number,
    upgradeCost: number, damage: number, currentAmmo: number, reserveText: string,
    compact: boolean, english: boolean): void {
    this.panel(ctx, x, y, w, h, p.equippedGun === gun.id ? C.cyanBright : C.amberBright);
    ctx.fillStyle = 'rgba(6, 12, 14, .93)'; ctx.fillRect(x + 2, y + 2, w - 4, h - 4);
    // Sparse measuring marks make the inspection bay feel like a field armorer's bench.
    ctx.strokeStyle = 'rgba(127, 157, 153, .20)'; ctx.lineWidth = 1;
    for (let i = 0; i < 8; i++) {
      const tx = x + 12 + i * (w - 24) / 7;
      ctx.beginPath(); ctx.moveTo(tx, y + 41); ctx.lineTo(tx, y + 46 + (i % 2) * 3); ctx.stroke();
    }
    ctx.fillStyle = owned ? C.text : C.textMuted; ctx.textAlign = 'left'; ctx.textBaseline = 'middle';
    ctx.font = `900 ${compact ? 13 : 16}px Segoe UI, Arial`;
    ctx.fillText(gun.shortName, x + 14, y + 20, w * .58);
    ctx.textAlign = 'right'; ctx.fillStyle = owned ? C.cyanBright : C.amberBright;
    ctx.font = `800 ${compact ? 8 : 9}px Segoe UI, Arial`;
    ctx.fillText(owned ? (p.equippedGun === gun.id ? (english ? 'Equipped' : 'Đang trang bị') : (english ? 'Recovered' : 'Đã thu hồi'))
      : (english ? `Mission ${gun.unlockStage}` : `Màn ${gun.unlockStage}`), x + w - 12, y + 20);

    const actionY = y + h - (compact ? 28 : 34), actionH = compact ? 23 : 28;
    const tinyCompact = compact && h < 205;
    const naturalArtH = (w - 30) * 60 / 170;
    const maxArtH = Math.max(35, Math.min(compact ? 88 : 142, h * (tinyCompact ? .29 : compact ? .38 : .40)));
    const artH = Math.min(naturalArtH, maxArtH);
    const artW = artH * 170 / 60;
    const artX = x + (w - artW) / 2;
    const artY = y + 31 + Math.max(0, (maxArtH - artH) / 2);
    ctx.save(); ctx.globalAlpha = owned ? 1 : .58;
    drawGunArt(ctx, artX, artY, artW, artH, gun.id, 'side');
    ctx.restore();

    const infoY = y + 31 + maxArtH + (compact ? 5 : 8);
    ctx.textAlign = 'left'; ctx.textBaseline = 'middle';
    if (tinyCompact) {
      ctx.fillStyle = owned ? C.amberBright : C.textMuted; ctx.font = '800 8px Segoe UI, Arial';
      ctx.fillText(owned ? `${currentAmmo}/${gun.magSize}  ·  ${english ? 'reserve' : 'dự trữ'} ${reserveText}`
        : (english ? 'Recover after the mission boss' : 'Nhặt sau khi hạ trùm'), x + 13, actionY - 6, w - 26);
    } else {
      ctx.fillStyle = C.textSoft; ctx.font = `700 ${compact ? 8 : 10}px Segoe UI, Arial`;
      const role = this.weaponRole(gun.id, english);
      ctx.fillText(role, x + 13, infoY + 6, w - 26);
      const damageText = english ? `${damage}${gun.pellets ? ` × ${gun.pellets}` : ''} damage  ·  ${gun.rpm} RPM  ·  ${gun.magSize}/mag`
        : `${damage}${gun.pellets ? ` × ${gun.pellets}` : ''} sát thương  ·  ${gun.rpm} RPM  ·  ${gun.magSize}/băng`;
      ctx.fillStyle = C.text; ctx.font = `800 ${compact ? 8 : 10}px Segoe UI, Arial`;
      ctx.fillText(damageText, x + 13, infoY + (compact ? 19 : 23), w - 26);
      ctx.fillStyle = owned ? C.amberBright : C.textMuted; ctx.font = `800 ${compact ? 8 : 10}px Segoe UI, Arial`;
      ctx.fillText(owned
        ? `${english ? 'Ammo' : 'Đạn'}  ${currentAmmo} / ${gun.magSize}     ${english ? 'Reserve' : 'Dự trữ'}  ${reserveText}`
        : (english ? 'Recover this weapon after defeating its mission boss.' : 'Hạ trùm màn tương ứng để thu hồi khẩu súng này.'),
        x + 13, infoY + (compact ? 32 : 42), w - 26);
    }

    if (!compact) {
      const stats: Array<[string, string]> = [
        [english ? 'Damage' : 'Sát thương', gun.pellets ? `${damage} × ${gun.pellets}` : String(damage)],
        [english ? 'Fire rate' : 'Tốc độ bắn', `${gun.rpm} RPM`],
        [english ? 'Magazine' : 'Băng đạn', `${gun.magSize} ${english ? 'rounds' : 'viên'}`],
        [english ? 'Reload' : 'Nạp đạn', `${gun.reloadDuration.toFixed(1)}s`],
      ];
      const statGap = 5, statW = (w - 26 - statGap) / 2, statH = 31;
      stats.forEach(([label, value], index) => {
        const col = index % 2, row = Math.floor(index / 2);
        const sx = x + 13 + col * (statW + statGap), sy = infoY + 56 + row * (statH + 5);
        ctx.fillStyle = 'rgba(31, 44, 45, .76)'; ctx.fillRect(sx, sy, statW, statH);
        ctx.strokeStyle = 'rgba(120, 151, 148, .38)'; ctx.lineWidth = 1; ctx.strokeRect(sx + .5, sy + .5, statW - 1, statH - 1);
        ctx.textAlign = 'left'; ctx.textBaseline = 'middle';
        ctx.fillStyle = C.textMuted; ctx.font = '700 7px Segoe UI, Arial'; ctx.fillText(label, sx + 7, sy + 9);
        ctx.fillStyle = C.text; ctx.font = '800 10px Segoe UI, Arial'; ctx.fillText(value, sx + 7, sy + 22, statW - 14);
      });

      const ammoY = y + h - 100, ammoH = 51;
      ctx.fillStyle = 'rgba(19, 30, 31, .92)'; ctx.fillRect(x + 12, ammoY, w - 24, ammoH);
      ctx.strokeStyle = 'rgba(194, 154, 101, .54)'; ctx.lineWidth = 1; ctx.strokeRect(x + 12.5, ammoY + .5, w - 25, ammoH - 1);
      ctx.textAlign = 'left'; ctx.textBaseline = 'middle';
      ctx.fillStyle = C.textMuted; ctx.font = '800 8px Segoe UI, Arial';
      ctx.fillText(english ? 'Loaded / reserve' : 'Trong băng / dự trữ', x + 20, ammoY + 12);
      ctx.textAlign = 'right'; ctx.fillStyle = owned ? C.amberBright : C.textMuted;
      ctx.font = '900 14px Segoe UI, Arial';
      ctx.fillText(owned ? `${currentAmmo}/${gun.magSize}  ·  ${reserveText}` : (english ? 'Recover from boss' : 'Nhặt sau khi hạ trùm'), x + w - 20, ammoY + 13);
      ctx.fillStyle = 'rgba(171, 190, 181, .16)'; ctx.fillRect(x + 20, ammoY + 30, w - 40, 5);
      const ammoRatio = gun.magSize > 0 ? Math.max(0, Math.min(1, currentAmmo / gun.magSize)) : 0;
      ctx.fillStyle = currentAmmo <= Math.ceil(gun.magSize * .2) ? C.dangerBright : C.health;
      ctx.fillRect(x + 20, ammoY + 30, (w - 40) * (owned ? ammoRatio : 0), 5);
      ctx.fillStyle = C.textSoft; ctx.font = '700 7px Segoe UI, Arial'; ctx.textAlign = 'left';
      ctx.fillText(owned ? (english ? `Level ${level}/3` : `Cấp súng ${level}/3`) : (english ? 'Not recovered' : 'Chưa thu hồi'), x + 20, ammoY + 44);
    }

    const actionGap = 4, actionX = x + 9, actionW = (w - 18 - actionGap * 2) / 3;
    const sidearm = gun.id === 'p9';
    const ammoCost = GUN_AMMO_COST[gun.id] ?? 0;
    const ammoFull = reserveText === '∞' || Number(reserveText) >= gun.magSize * 12;
    const labels = [
      p.equippedGun === gun.id ? (english ? 'Equipped' : 'Đang dùng') : english ? 'Equip' : 'Trang bị',
      !owned ? (english ? 'Not recovered' : 'Chưa có súng') : level >= 3 ? (english ? 'Max level' : 'Tối đa') : `${english ? 'Upgrade' : 'Nâng'} · ${upgradeCost}`,
      sidearm ? (english ? 'Unlimited' : 'Vô hạn') : !owned ? (english ? 'Not recovered' : 'Chưa có súng')
        : ammoFull ? (english ? 'Ammo full' : 'Đủ đạn') : `${english ? 'Buy' : 'Mua'} +${gun.magSize * 2} · ${ammoCost}`,
    ];
    const actions = [`gun:${gun.id}`, `upgrade:${gun.id}`, `buyammo:${gun.id}`];
    const disabled = [!owned || p.equippedGun === gun.id,
      !owned || level >= 3 || p.credits < upgradeCost,
      sidearm || !owned || ammoFull || p.credits < ammoCost];
    for (let i = 0; i < actions.length; i++) {
      this.add(actionX + i * (actionW + actionGap), actionY, actionW, actionH, labels[i], actions[i], disabled[i]);
    }
  }

  private weaponRole(id: string, english: boolean): string {
    const roles: Record<string, [string, string]> = {
      p9: ['Súng lục · đạn dự trữ vô hạn', 'Sidearm · unlimited reserve ammo'],
      ar7: ['Súng trường · cân bằng cho giao tranh tầm trung', 'Rifle · balanced mid-range fire'],
      smg9: ['SMG · tốc độ bắn cao ở cự ly gần', 'SMG · high rate of fire at close range'],
      sg12: ['Shotgun · nhiều pellet trong một phát bắn', 'Shotgun · multiple pellets per shot'],
      dmr55: ['DMR · phát bắn chính xác, sát thương cao', 'DMR · precise, high-damage shots'],
      bulldog: ['Shotgun nặng · tỏa rộng, uy lực lớn', 'Heavy shotgun · wide, hard-hitting spread'],
      lmg6: ['LMG · băng đạn lớn cho hỏa lực liên tục', 'LMG · large magazine for sustained fire'],
      flamer8: ['Súng phun lửa · thiêu đốt ở cự ly gần', 'Flamethrower · burns targets at close range'],
      rpg4: ['RPG · đầu đạn nổ gây sát thương diện rộng', 'RPG · explosive rounds deal area damage'],
      rail_lance: ['Rail Lance · đạn năng lượng xuyên mục tiêu', 'Rail Lance · energy rounds pierce targets'],
    };
    const role = roles[id] ?? roles.ar7;
    return english ? role[1] : role[0];
  }

  private drawGear(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number,
    p: SaveSystem['data']['campaign'], narrow: boolean): void {
    const english = this.language === 'en';
    const gearY = y + h - 143, gearH = 62, gap = 6, cellW = (w - 44 - gap * 2) / 3;
    const items = [
      { icon: 'flashlight' as const, title: english ? `Flashlight · level ${p.flashlightLevel}/3` : `Đèn pin · cấp ${p.flashlightLevel}/3`, detail: p.flashlightLevel >= 3 ? (english ? 'Maximum brightness' : 'Độ sáng tối đa') : (english ? 'Longer beam' : 'Chiếu xa hơn'), action: 'flashlight', cost: 95 + p.flashlightLevel * 75, disabled: p.flashlightLevel >= 3 },
      { icon: 'armor' as const, title: english ? `Armor · level ${p.armorLevel}/3` : `Áo giáp · cấp ${p.armorLevel}/3`, detail: p.armorLevel ? (english ? `Reduces damage by ${[0, 10, 18, 25][p.armorLevel]}%` : `Giảm ${[0, 10, 18, 25][p.armorLevel]}% sát thương`) : (english ? 'Reduces incoming damage' : 'Giảm sát thương nhận vào'), action: 'armor', cost: [150, 260, 390][p.armorLevel] ?? 390, disabled: p.armorLevel >= 3 },
      { icon: 'medical' as const, title: english ? `Medical kit · ${p.medKits}/5` : `Túi cứu thương · ${p.medKits}/5`, detail: english ? 'Auto-use · restores 50% HP' : 'Tự dùng · hồi 50% máu', action: 'med', cost: 70, disabled: p.medKits >= 5 },
    ];
    items.forEach((item, i) => {
      const bx = x + 22 + i * (cellW + gap);
      this.panel(ctx, bx, gearY, cellW, gearH, i === 1 ? '#a7c888' : i === 2 ? '#77b78e' : C.cyanBright);
      ctx.fillStyle = C.text; ctx.textAlign = 'left'; ctx.font = `bold ${narrow ? 8 : 10}px Segoe UI, Arial`;
      const textX = bx + (narrow ? 31 : 42);
      this.drawGearIcon(ctx, bx + (narrow ? 17 : 23), gearY + 18, item.icon, narrow ? .34 : .46);
      ctx.fillText(item.title, textX, gearY + 13, cellW - (textX - bx) - 5);
      ctx.fillStyle = C.textSoft; ctx.font = `${narrow ? 7 : 9}px Segoe UI, Arial`;
      ctx.fillText(item.detail, textX, gearY + 26, cellW - (textX - bx) - 5);
      const label = item.disabled ? (item.action === 'med' ? (english ? 'Full' : 'Đầy túi') : (english ? 'Max level' : 'Tối đa')) : `${english ? 'Buy' : 'Mua'} · ${item.cost}`;
      this.add(bx + 5, gearY + 33, cellW - 10, 23, label, item.action,
        item.disabled || p.credits < item.cost);
    });
  }

  private dronePrice(level: number): number { return 115 + level * 65; }

  private gunUpgradeCost(level: number): number {
    return GUN_UPGRADE_COSTS[Math.max(0, Math.min(GUN_UPGRADE_COSTS.length - 1, level))];
  }

  private drawDroneShowcase(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number,
    p: SaveSystem['data']['campaign'], compact: boolean, english: boolean): void {
    const level = Math.min(DRONE_UPGRADE.maxLevel, p.cardLevels.drone ?? 0);
    const maxed = level >= DRONE_UPGRADE.maxLevel;
    const cost = this.dronePrice(level);
    const buttonH = compact ? 23 : 28, buttonY = y + h - buttonH - 8;
    this.panel(ctx, x, y, w, h, C.cyanBright);
    ctx.fillStyle = 'rgba(6, 12, 14, .93)'; ctx.fillRect(x + 2, y + 2, w - 4, h - 4);
    ctx.textAlign = 'left'; ctx.textBaseline = 'middle'; ctx.fillStyle = C.cyanBright;
    ctx.font = `900 ${compact ? 12 : 16}px Segoe UI, Arial`;
    ctx.fillText(english ? 'SUPPORT DRONE' : 'DRONE HỘ VỆ', x + 14, y + 20, w - 28);

    const iconScale = Math.min(compact ? .92 : 1.5, w / 105, Math.max(.45, (buttonY - y - 74) / 54));
    this.drawDroneIcon(ctx, x + w / 2, y + Math.min(compact ? 58 : 86, Math.max(48, h * .25)), iconScale);
    ctx.textAlign = 'center'; ctx.fillStyle = C.text; ctx.font = `800 ${compact ? 12 : 18}px Segoe UI, Arial`;
    ctx.fillText(english ? 'Automatic fire support' : 'Hỗ trợ hỏa lực tự động', x + w / 2, y + h * (compact ? .48 : .47), w - 20);
    ctx.fillStyle = C.textSoft; ctx.font = `${compact ? 8 : 11}px Segoe UI, Arial`;
    if (compact) {
      ctx.fillText(english ? 'Orbits and attacks nearby targets.' : 'Bay quanh, tự bắn mục tiêu gần.', x + w / 2, y + h * .60, w - 18);
    } else {
      this.wrap(ctx, english ? 'The drone circles the player and fires at the nearest target. Each level adds another drone.'
        : 'Drone bay quanh nhân vật và tự động bắn mục tiêu gần nhất. Mỗi cấp thêm một drone.',
      x + 18, y + h * .57, w - 36, 15, 3);
    }

    const pipGap = 18, pipStart = x + w / 2 - (DRONE_UPGRADE.maxLevel - 1) * pipGap / 2;
    const pipY = buttonY - (compact ? 20 : 26);
    for (let i = 0; i < DRONE_UPGRADE.maxLevel; i++) {
      ctx.beginPath(); ctx.arc(pipStart + i * pipGap, pipY, compact ? 4 : 5, 0, Math.PI * 2);
      ctx.fillStyle = i < level ? C.cyanBright : C.borderSoft; ctx.fill();
    }
    ctx.fillStyle = C.textSoft; ctx.font = `bold ${compact ? 8 : 10}px Segoe UI, Arial`;
    ctx.textAlign = 'center';
    ctx.fillText(english ? `Level ${level}/${DRONE_UPGRADE.maxLevel} · ${level} active`
      : `Cấp ${level}/${DRONE_UPGRADE.maxLevel} · ${level} đang hoạt động`, x + w / 2, pipY - 11);
    const label = maxed ? (english ? 'Maximum level reached' : 'Đã đạt cấp tối đa')
      : english ? `Upgrade · ${cost} credits` : `Nâng cấp · ${cost} tín dụng`;
    this.add(x + 9, buttonY, w - 18, buttonH, label, 'drone', maxed || p.credits < cost);
  }

  /** Original Canvas line art; keep the drone consistent with the game's flat military UI. */
  private drawDroneIcon(ctx: CanvasRenderingContext2D, cx: number, cy: number, scale: number): void {
    ctx.save(); ctx.translate(cx, cy); ctx.scale(scale, scale);
    ctx.lineCap = 'round'; ctx.lineJoin = 'round';
    ctx.strokeStyle = '#9bb8b5'; ctx.lineWidth = 5;
    for (const [dx, dy] of [[-37, -23], [37, -23], [-37, 23], [37, 23]]) {
      ctx.beginPath(); ctx.moveTo(dx * .35, dy * .35); ctx.lineTo(dx, dy); ctx.stroke();
      ctx.beginPath(); ctx.ellipse(dx, dy, 17, 5, dx * dy < 0 ? -.25 : .25, 0, Math.PI * 2); ctx.stroke();
      ctx.strokeStyle = '#657775'; ctx.lineWidth = 2;
      ctx.beginPath(); ctx.moveTo(dx - 10, dy); ctx.lineTo(dx + 10, dy); ctx.stroke();
      ctx.strokeStyle = '#9bb8b5'; ctx.lineWidth = 5;
    }
    ctx.fillStyle = '#263536'; ctx.strokeStyle = '#c7d3c9'; ctx.lineWidth = 2.5;
    ctx.beginPath(); ctx.roundRect(-23, -16, 46, 32, 8); ctx.fill(); ctx.stroke();
    ctx.fillStyle = '#63d8dc'; ctx.beginPath(); ctx.roundRect(-6, -9, 12, 18, 4); ctx.fill();
    ctx.fillStyle = '#d2c496'; ctx.fillRect(-16, -3, 5, 6); ctx.fillRect(11, -3, 5, 6);
    ctx.fillStyle = '#374847'; ctx.fillRect(-11, 17, 22, 5);
    ctx.restore();
  }

  /** Small original line-art supply icons, drawn in Canvas to stay sharp at every UI scale. */
  private drawGearIcon(ctx: CanvasRenderingContext2D, cx: number, cy: number,
    kind: 'flashlight' | 'armor' | 'medical', scale: number): void {
    ctx.save(); ctx.translate(cx, cy); ctx.scale(scale, scale);
    ctx.lineJoin = 'round'; ctx.lineCap = 'round';
    if (kind === 'flashlight') {
      ctx.save(); ctx.rotate(-.34);
      ctx.fillStyle = '#293638'; ctx.strokeStyle = '#a9c2b6'; ctx.lineWidth = 2.4;
      ctx.beginPath(); ctx.moveTo(-19, -5); ctx.lineTo(10, -5); ctx.lineTo(15, -8);
      ctx.lineTo(21, -6); ctx.lineTo(21, 6); ctx.lineTo(15, 8); ctx.lineTo(10, 5); ctx.lineTo(-19, 5); ctx.closePath(); ctx.fill(); ctx.stroke();
      ctx.fillStyle = '#53cbd0'; ctx.beginPath(); ctx.moveTo(17, -4); ctx.lineTo(25, -7); ctx.lineTo(25, 7); ctx.lineTo(17, 4); ctx.closePath(); ctx.fill();
      ctx.strokeStyle = '#e4d2a3'; ctx.lineWidth = 1.6;
      ctx.beginPath(); ctx.moveTo(-7, -5); ctx.lineTo(-9, 5); ctx.moveTo(-13, -4); ctx.lineTo(-15, 4); ctx.stroke();
      ctx.fillStyle = '#bd7653'; ctx.fillRect(1, -8, 5, 3);
      ctx.restore();
    } else if (kind === 'armor') {
      ctx.fillStyle = '#334442'; ctx.strokeStyle = '#b0c49b'; ctx.lineWidth = 2.4;
      ctx.beginPath(); ctx.moveTo(-12, -19); ctx.lineTo(-4, -16); ctx.lineTo(0, -19); ctx.lineTo(5, -16);
      ctx.lineTo(13, -19); ctx.lineTo(18, -10); ctx.lineTo(14, -4); ctx.lineTo(13, 15);
      ctx.lineTo(7, 19); ctx.lineTo(0, 15); ctx.lineTo(-7, 19); ctx.lineTo(-14, 15);
      ctx.lineTo(-14, -4); ctx.lineTo(-18, -10); ctx.closePath(); ctx.fill(); ctx.stroke();
      ctx.strokeStyle = '#718d77'; ctx.lineWidth = 2;
      ctx.beginPath(); ctx.moveTo(-8, -15); ctx.lineTo(-6, -5); ctx.lineTo(-10, 5); ctx.moveTo(8, -15); ctx.lineTo(6, -5); ctx.lineTo(10, 5); ctx.stroke();
      ctx.fillStyle = '#718d77'; ctx.fillRect(-5, -2, 10, 10);
      ctx.strokeStyle = '#d5c99e'; ctx.lineWidth = 1.5;
      ctx.beginPath(); ctx.moveTo(-4, 11); ctx.lineTo(4, 11); ctx.stroke();
    } else {
      ctx.fillStyle = '#263b3b'; ctx.strokeStyle = '#83c39a'; ctx.lineWidth = 2.4;
      ctx.beginPath(); ctx.roundRect(-17, -12, 34, 27, 4); ctx.fill(); ctx.stroke();
      ctx.beginPath(); ctx.moveTo(-8, -12); ctx.lineTo(-8, -18); ctx.quadraticCurveTo(0, -24, 8, -18); ctx.lineTo(8, -12); ctx.stroke();
      ctx.fillStyle = '#d7e3d0'; ctx.fillRect(-3, -7, 6, 17); ctx.fillRect(-9, -1, 18, 6);
      ctx.strokeStyle = '#b2805a'; ctx.lineWidth = 1.4;
      ctx.beginPath(); ctx.moveTo(-13, 11); ctx.lineTo(-8, 11); ctx.moveTo(8, 11); ctx.lineTo(13, 11); ctx.stroke();
    }
    ctx.restore();
  }

  private results(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number): void {
    const s = STAGES[this.selectedStage];
    const english = this.language === 'en';
    const stage = getStageCopy(s, this.language);
    this.title(ctx, `${english ? 'Mission complete' : 'Đã hoàn thành'} · ${stage.name}`, x + 22, y + 82);
    const progress = Math.min(1, Math.max(0, (performance.now() - this.resultAnimationStartedAt) / 1700));
    const eased = 1 - Math.pow(1 - progress, 3);
    const countedTotal = Math.round(this.result.previousTotalScore
      + (this.result.totalScore - this.result.previousTotalScore) * eased);
    const formatScore = (value: number) => Math.max(0, value).toLocaleString(english ? 'en-US' : 'vi-VN');
    const time = `${Math.floor(this.result.time / 60)}:${String(Math.floor(this.result.time % 60)).padStart(2, '0')}`;
    const rows = english ? [
      `Campaign score: ${formatScore(countedTotal)} (+${formatScore(this.result.scoreAdded)})`,
      `Mission score: ${formatScore(this.result.score)}`,
      `Time: ${time} · Kills: ${this.result.kills}`,
      `Boss defeated: ${stage.bossName} · Supplies secured: ${this.result.optional}`,
      `First-clear reward: +${this.result.reward} credits`,
      this.result.newStage ? `Mission ${this.result.newStage} unlocked` : 'No new mission unlocked',
    ] : [
      `Tổng điểm Chiến dịch: ${formatScore(countedTotal)} (+${formatScore(this.result.scoreAdded)})`,
      `Điểm màn này: ${formatScore(this.result.score)}`,
      `Thời gian: ${time} · Quái hạ gục: ${this.result.kills}`,
      `Đã hạ trùm: ${stage.bossName} · Tiếp tế thu hồi: ${this.result.optional}`,
      `Thưởng lần đầu: +${this.result.reward} tín dụng`,
      this.result.newStage ? `Đã mở màn ${this.result.newStage}` : 'Chưa mở màn mới',
    ];
    ctx.textAlign = 'left'; ctx.font = '15px Segoe UI, Arial';
    rows.forEach((line, i) => {
      ctx.fillStyle = i === 0 ? C.amberBright : i === 5 ? C.text : C.textSoft;
      if (i === 0) ctx.font = 'bold 17px Segoe UI, Arial';
      else ctx.font = '15px Segoe UI, Arial';
      ctx.fillText(line, x + 26, y + 125 + i * Math.min(49, (h - 225) / rows.length), w - 50);
    });
    if (w < 600) {
      this.add(x + 22, y + h - 96, w - 44, 34, english ? 'Armory and drone' : 'Kho vũ khí và drone', 'post_stage_armory');
      const bw = (w - 52) / 2;
      this.add(x + 22, y + h - 54, bw, 34, english ? 'Missions' : 'Bản đồ', 'stages');
      this.add(x + w - bw - 22, y + h - 54, bw, 34, english ? 'Retry' : 'Chơi lại', 'retry');
    } else {
      const bw = Math.min(220, (w - 64) / 3);
      this.add(x + 22, y + h - 54, bw, 36, english ? 'Missions' : 'Bản đồ', 'stages');
      this.add(x + (w - bw) / 2, y + h - 54, bw, 36, english ? 'Retry' : 'Chơi lại', 'retry');
      this.add(x + w - bw - 22, y + h - 54, bw, 36, english ? 'Armory and drone' : 'Kho vũ khí và drone', 'post_stage_armory');
    }
  }

  private failure(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number): void {
    const english = this.language === 'en';
    const stage = getStageCopy(STAGES[this.selectedStage], this.language);
    this.title(ctx, english ? 'Mission failed' : 'Nhiệm vụ thất bại', x + 22, y + 82);
    this.copy(ctx, english ? 'After-action report' : 'Báo cáo', english
      ? `${stage.name} · ${this.result.kills} kills · survived ${Math.floor(this.result.time)} seconds`
      : `${stage.name} · hạ ${this.result.kills} quái · sống sót ${Math.floor(this.result.time)} giây`, x + 24, y + 130, w - 48);
    this.copy(ctx, this.impossibleDeath ? (english ? 'No second chance' : 'Không còn cơ hội') : (english ? 'Campaign status' : 'Tiến trình'),
      this.impossibleDeath
        ? english ? 'The Campaign save has been erased. Start a new game from Mission 1.' : 'Hồ sơ Chiến dịch đã bị xóa. Game mới sẽ bắt đầu từ màn 1.'
        : english ? 'Mission incomplete. Your weapons, drone, remaining ammo, and unused supplies are retained.'
          : 'Màn chưa hoàn thành. Súng, drone, đạn còn lại và vật tư chưa dùng vẫn được giữ.',
      x + 24, y + 215, w - 48);
    const bw = Math.min(210, (w - 60) / 2);
    if (this.impossibleDeath) {
      this.add(x + 22, y + h - 54, bw, 36, english ? 'Main menu' : 'Menu chính', 'main');
      this.add(x + w - bw - 22, y + h - 54, bw, 36, english ? 'New game' : 'Game mới', 'retry');
    } else {
      const reviveLabel = this.reviveAdPending ? (english ? 'Loading ad…' : 'Đang tải quảng cáo…')
        : this.reviveAdAvailable ? (english ? 'Revive · watch an ad' : 'Hồi sinh · xem quảng cáo')
        : (english ? 'Revive unavailable · no ad provider' : 'Không thể hồi sinh · chưa có quảng cáo');
      this.add(x + 22, y + h - 96, w - 44, 32, reviveLabel, 'revive_ad',
        !this.canWatchRevive || !this.reviveAdAvailable || this.reviveAdPending);
      this.add(x + 22, y + h - 54, bw, 36, english ? 'Armory' : 'Kho vũ khí', 'return_armory');
      this.add(x + w - bw - 22, y + h - 54, bw, 36, english ? 'Retry' : 'Thử lại', 'retry');
    }
  }

  private title(ctx: CanvasRenderingContext2D, text: string, x: number, y: number): void { ctx.textAlign = 'left'; ctx.fillStyle = C.text; ctx.font = 'bold 22px Segoe UI, Arial'; ctx.fillText(sentenceCaseDisplay(text, this.language), x, y); }
  private copy(ctx: CanvasRenderingContext2D, label: string, body: string, x: number, y: number, width: number): void {
    ctx.textAlign = 'left'; ctx.fillStyle = C.amberBright; ctx.font = 'bold 12px Segoe UI, Arial'; ctx.fillText(sentenceCaseDisplay(label, this.language), x, y);
    ctx.fillStyle = C.textSoft; ctx.font = '13px Segoe UI, Arial'; this.wrap(ctx, body, x, y + 23, width, 18, 2);
  }
  private wrap(ctx: CanvasRenderingContext2D, str: string, x: number, y: number, width: number, lineH: number, maxLines: number): void {
    // Wrapped copy uses x as its left edge. Callers may have left the canvas in centered mode
    // after drawing a heading, which otherwise makes the text spill outside its card.
    ctx.save();
    ctx.textAlign = 'left';
    const words = str.split(' '); let line = '', lines = 0;
    for (const word of words) {
      const next = line ? `${line} ${word}` : word;
      if (ctx.measureText(next).width > width && line) {
        ctx.fillText(line, x, y + lines * lineH);
        lines++;
        line = word;
        if (lines >= maxLines) { ctx.restore(); return; }
      }
      else line = next;
    }
    if (lines < maxLines) ctx.fillText(line, x, y + lines * lineH);
    ctx.restore();
  }
  private panel(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, stroke: string): void {
    ctx.fillStyle = C.panelRaised; ctx.fillRect(x, y, w, h); ctx.strokeStyle = stroke; ctx.lineWidth = 1.5; ctx.strokeRect(x, y, w, h);
  }
  private add(x: number, y: number, w: number, h: number, label: string, action: string, disabled = false): void { this.buttons.push({ x, y, w, h, label, action, disabled }); }
  private drawButton(ctx: CanvasRenderingContext2D, b: Button): void {
    if (!b.label) return;
    const normalizedLabel = b.label.toLocaleLowerCase('vi-VN');
    const selected = b.disabled && (b.action.startsWith('tab:') || normalizedLabel === 'đang chọn' || normalizedLabel === 'đang dùng' || normalizedLabel === 'selected' || normalizedLabel === 'equipped');
    ctx.fillStyle = selected ? C.selected : b.disabled ? '#30383c' : '#49675c'; ctx.fillRect(b.x, b.y, b.w, b.h);
    ctx.strokeStyle = selected ? C.selectedBorder : b.disabled ? C.borderSoft : C.health; ctx.strokeRect(b.x, b.y, b.w, b.h);
    ctx.fillStyle = b.disabled && !selected ? C.textMuted : C.text; ctx.textAlign = 'center'; ctx.textBaseline = 'middle';
    ctx.font = `bold ${b.w < 140 ? 10 : 12}px Segoe UI, Arial`; ctx.fillText(sentenceCaseDisplay(b.label, this.language), b.x + b.w / 2, b.y + b.h / 2, b.w - 8); ctx.textBaseline = 'alphabetic';
  }

  private characterName(id: string, fallback: string): string {
    const names = this.language === 'en'
      ? { survivor: 'Survivor', soldier: 'Soldier', scout: 'Scout', medic: 'Medic', engineer: 'Engineer', berserker: 'Berserker' }
      : { survivor: 'Người sống sót', soldier: 'Lính', scout: 'Trinh sát', medic: 'Quân y', engineer: 'Kỹ sư', berserker: 'Cuồng chiến' };
    return names[id as keyof typeof names] ?? fallback;
  }

  private characterDescription(id: string, fallback: string): string {
    const descriptions = this.language === 'en'
      ? { survivor: 'Picks up items from 20% farther away', soldier: 'Deals 20% more damage', scout: 'Moves 20% faster', medic: 'Has 25% more maximum HP', engineer: 'Fires 18% faster', berserker: 'Takes 18% less damage' }
      : { survivor: 'Nhặt vật phẩm xa hơn 20%', soldier: 'Gây thêm 20% sát thương', scout: 'Di chuyển nhanh hơn 20%', medic: 'Tăng 25% máu tối đa', engineer: 'Tăng 18% tốc độ bắn', berserker: 'Giảm 18% sát thương nhận vào' };
    return descriptions[id as keyof typeof descriptions] ?? fallback;
  }

  private zombieName(id: string): string {
    return localizeZombieName(id, this.language);
  }

  private weaponType(type: string): string {
    if (this.language === 'en') return type === 'smg' ? 'SMG' : type.toLocaleLowerCase('en-US');
    return type === 'rifle' ? 'Súng trường' : type === 'shotgun' ? 'Shotgun' : 'SMG';
  }
}
