import { CHARACTERS, STAGES } from '../data/meta';
import { SaveSystem } from '../systems/save';
import { UPGRADES } from '../data/upgrades';
import { createCampaignGunDefs } from '../systems/gun-loadout';
import { drawGunArt, drawHunterPortrait } from '../graphics/campaign-menu-art';
import { UI_PALETTE as C } from './palette';
import { createQuarantineBackdrop } from './horror-texture';

export type CampaignPage = 'character' | 'stages' | 'briefing' | 'armory' | 'result' | 'failure';
type Button = { x: number; y: number; w: number; h: number; label: string; action: string; disabled?: boolean; selected?: boolean };
const GUNS = createCampaignGunDefs();
const DRONE_UPGRADE = UPGRADES.find(def => def.id === 'drone')!;

/** Canvas campaign front-end. Buttons and hitboxes are generated by the same draw pass. */
export class CampaignUI {
  page: CampaignPage = 'character';
  selectedStage = 0;
  stagePage = 0;
  result = { time: 0, kills: 0, reward: 0, newStage: 0, optional: 0 };
  message = '';
  armoryTab: 'guns' | 'drone' = 'guns';
  gunPage = 0;
  focusedCharacter = 'survivor';
  private buttons: Button[] = [];
  private backdrop?: HTMLCanvasElement;

  click(x: number, y: number, save: SaveSystem): string | null {
    const b = this.buttons.findLast(v => x >= v.x && x <= v.x + v.w && y >= v.y && y <= v.y + v.h);
    if (!b || b.disabled) return null;
    const p = save.data.campaign;
    this.message = '';
    if (b.action === 'back') {
      this.page = this.page === 'character' ? 'character' : this.page === 'armory' ? 'character' : this.page === 'stages' ? 'armory' : 'stages';
      return this.page === 'character' && b.label.includes('MENU') ? 'main' : null;
    }
    if (b.action === 'main') return 'main';
    if (b.action === 'stages') { this.page = 'stages'; return null; }
    if (b.action === 'briefing') { this.page = 'briefing'; return null; }
    if (b.action === 'armory') { this.page = 'armory'; return null; }
    if (b.action === 'post_stage_armory') {
      this.page = 'armory';
      this.armoryTab = 'guns';
      return null;
    }
    if (b.action === 'tab:guns' || b.action === 'tab:drone') { this.armoryTab = b.action === 'tab:guns' ? 'guns' : 'drone'; return null; }
    if (b.action.startsWith('gunpage:')) { this.gunPage = Number(b.action.slice(8)); return null; }
    if (b.action.startsWith('focus:')) { this.focusedCharacter = b.action.slice(6); return null; }
    if (b.action === 'drone') {
      const level = p.cardLevels.drone ?? 0;
      if (level >= DRONE_UPGRADE.maxLevel) return null;
      const cost = this.dronePrice(level);
      if (!save.spendCampaign(cost)) { this.message = 'CHƯA ĐỦ TÍN DỤNG'; return null; }
      p.cardLevels.drone = level + 1; save.save(); this.message = `ĐÃ NÂNG DRONE · CẤP ${level + 1}`; return null;
    }
    if (b.action === 'start') return 'start';
    if (b.action === 'retry') return 'retry';
    if (b.action === 'return_armory') { this.page = 'armory'; return null; }
    if (b.action === 'next') {
      this.selectedStage = Math.min(STAGES.length - 1, this.selectedStage + 1);
      this.page = 'briefing'; return null;
    }
    if (b.action.startsWith('page:')) { this.stagePage = Number(b.action.slice(5)); return null; }
    if (b.action.startsWith('stage:')) {
      const index = Number(b.action.slice(6));
      if (index + 1 <= p.unlockedStage) { this.selectedStage = index; this.page = 'briefing'; }
      return null;
    }
    if (b.action.startsWith('char:')) {
      const id = b.action.slice(5);
      const c = CHARACTERS.find(v => v.id === id)!;
      this.focusedCharacter = id;
      if (!p.unlockedCharacters.includes(id)) {
        if (!save.spendCampaign(c.cost)) { this.message = 'CHƯA ĐỦ TÍN DỤNG'; return null; }
        p.unlockedCharacters.push(id);
      }
      p.selectedCharacter = id; save.save(); return null;
    }
    if (b.action.startsWith('gun:')) {
      const id = b.action.slice(4);
      const definition = GUNS.find(g => g.id === id);
      if (!definition || !p.ownedGuns.includes(id)) { this.message = 'HẠ BOSS VÀ NHẶT SÚNG TRÊN MAP TRƯỚC'; return null; }
      p.equippedGun = id; save.save(); return null;
    }
    if (b.action.startsWith('upgrade:')) {
      const id = b.action.slice(8), level = p.gunLevels[id] ?? 0;
      if (level >= 3 || !p.ownedGuns.includes(id)) return null;
      if (!save.spendCampaign(75 * (level + 1))) { this.message = 'CHƯA ĐỦ TÍN DỤNG'; return null; }
      p.gunLevels[id] = level + 1; save.save(); return null;
    }
    if (b.action === 'ammo') {
      if (!save.spendCampaign(30)) { this.message = 'CHƯA ĐỦ TÍN DỤNG'; return null; }
      p.ammoPacks = Math.min(4, p.ammoPacks + 1); save.save(); return null;
    }
    if (b.action === 'med') {
      if (!save.spendCampaign(45)) { this.message = 'CHƯA ĐỦ TÍN DỤNG'; return null; }
      p.medKits = Math.min(3, p.medKits + 1); save.save(); return null;
    }
    return null;
  }

  draw(ctx: CanvasRenderingContext2D, w: number, h: number, save: SaveSystem): void {
    this.buttons.length = 0;
    const p = save.data.campaign;
    if (!this.backdrop || this.backdrop.width !== Math.ceil(w) || this.backdrop.height !== Math.ceil(h)) {
      this.backdrop = createQuarantineBackdrop(w, h);
    }
    ctx.drawImage(this.backdrop, 0, 0, w, h);
    ctx.fillStyle = 'rgba(4, 7, 9, 0.32)'; ctx.fillRect(0, 0, w, h);
    const panelW = Math.min(980, w - 20), panelH = Math.min(760, h - 20);
    const x = (w - panelW) / 2, y = (h - panelH) / 2;
    const narrow = panelW < 600;
    ctx.fillStyle = C.background; ctx.fillRect(x, y, panelW, panelH);
    ctx.strokeStyle = C.border; ctx.lineWidth = 2; ctx.strokeRect(x, y, panelW, panelH);
    ctx.fillStyle = C.textSoft; ctx.textAlign = 'left'; ctx.font = 'bold 15px Segoe UI, Arial';
    ctx.fillText(`CHIẾN DỊCH  /  ${this.page.toUpperCase()}`, x + 20, y + 30);
    ctx.textAlign = 'right'; ctx.fillStyle = C.amberBright; ctx.fillText(`${p.credits} TÍN DỤNG`, x + panelW - 20, y + 30);
    ctx.fillStyle = C.borderSoft; ctx.fillRect(x + 20, y + 42, panelW - 40, 1);
    if (this.page === 'character') this.characters(ctx, x, y, panelW, panelH, p, narrow);
    if (this.page === 'stages') this.stages(ctx, x, y, panelW, panelH, p, narrow);
    if (this.page === 'briefing') this.briefing(ctx, x, y, panelW, panelH, narrow, p);
    if (this.page === 'armory') this.armory(ctx, x, y, panelW, panelH, p, narrow);
    if (this.page === 'result') this.results(ctx, x, y, panelW, panelH);
    if (this.page === 'failure') this.failure(ctx, x, y, panelW, panelH);
    if (this.message) { ctx.fillStyle = C.dangerBright; ctx.textAlign = 'center'; ctx.font = 'bold 13px Segoe UI, Arial'; ctx.fillText(this.message, w / 2, y + panelH - 67); }
    this.buttons.forEach(b => this.drawButton(ctx, b));
  }

  private characters(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, p: SaveSystem['data']['campaign'], narrow: boolean): void {
    this.title(ctx, 'CHỌN NHÂN VẬT', x + 22, y + 78);
    const portraitW = narrow ? Math.min(155, w * .38) : Math.min(285, w * .34);
    const portraitH = Math.max(145, Math.min(h - 195, narrow ? 210 : 330));
    const focused = CHARACTERS.find(c => c.id === this.focusedCharacter) ?? CHARACTERS[0];
    this.panel(ctx, x + 22, y + 98, portraitW, portraitH, focused.color);
    drawHunterPortrait(ctx, x + 30, y + 110, portraitW - 16, portraitH - 50, focused.id, focused.color);
    ctx.fillStyle = C.text; ctx.font = `bold ${narrow ? 13 : 17}px Segoe UI, Arial`; ctx.textAlign = 'center';
    ctx.fillText(focused.name.toUpperCase(), x + 22 + portraitW / 2, y + 98 + portraitH - 18, portraitW - 12);
    ctx.textAlign = 'left'; ctx.fillStyle = C.textSoft; ctx.font = `bold ${narrow ? 10 : 12}px Segoe UI, Arial`;
    ctx.fillText(`HP ${Math.round((focused.bonuses.hp ?? 1) * 100)}   TỐC ${Math.round((focused.bonuses.speed ?? 1) * 100)}%`, x + 23, y + 120 + portraitH, portraitW);
    ctx.fillText(`SÁT THƯƠNG ${Math.round((focused.bonuses.damage ?? 1) * 100)}%`, x + 23, y + 139 + portraitH, portraitW);
    const listX = x + 32 + portraitW, listW = w - portraitW - 54;
    const cardH = Math.min(narrow ? 56 : 67, (h - 195) / 6 - 4);
    CHARACTERS.forEach((c, i) => {
      const bx = listX, by = y + 98 + i * (cardH + 5), cardW = listW;
      const owned = p.unlockedCharacters.includes(c.id), selected = p.selectedCharacter === c.id;
      this.panel(ctx, bx, by, cardW, cardH, this.focusedCharacter === c.id ? C.amberBright : C.borderSoft);
      ctx.fillStyle = c.color; ctx.fillRect(bx + 7, by + 8, 4, cardH - 16);
      ctx.fillStyle = C.text; ctx.font = `bold ${narrow ? 11 : 15}px Segoe UI, Arial`; ctx.textAlign = 'left'; ctx.fillText(c.name.toUpperCase(), bx + 18, by + 19, cardW - 95);
      if (cardH >= 45) { ctx.fillStyle = C.textSoft; ctx.font = `${narrow ? 9 : 11}px Segoe UI, Arial`; ctx.fillText(c.description, bx + 18, by + 35, cardW - 93); }
      this.add(bx + cardW - (narrow ? 74 : 108), by + 8, narrow ? 67 : 100, cardH - 16,
        selected ? 'ĐANG CHỌN' : owned ? 'CHỌN' : `MỞ ${c.cost}`, `char:${c.id}`, selected || (!owned && p.credits < c.cost));
      this.add(bx + 12, by + 2, Math.max(1, cardW - (narrow ? 90 : 125)), cardH - 4, '', `focus:${c.id}`);
    });
    this.add(x + 22, y + h - 52, Math.min(140, (w - 52) / 2), 34, 'VỀ MENU', 'main');
    this.add(x + w - Math.min(205, (w - 52) / 2) - 22, y + h - 52, Math.min(205, (w - 52) / 2), 34, 'CHUẨN BỊ →', 'armory');
  }

  private stages(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, p: SaveSystem['data']['campaign'], narrow: boolean): void {
    this.title(ctx, 'TUYẾN CHIẾN DỊCH', x + 22, y + 78);
    const start = narrow ? this.stagePage * 5 : 0;
    const list = STAGES.slice(start, start + (narrow ? 5 : 10));
    const cols = narrow ? 1 : 2, gap = 8, bw = (w - 44 - gap * (cols - 1)) / cols;
    const rowH = Math.min(narrow ? 63 : 88, (h - 188) / (narrow ? 5 : 5) - gap);
    list.forEach((s, i) => {
      const bx = x + 22 + (i % cols) * (bw + gap), by = y + 95 + Math.floor(i / cols) * (rowH + gap);
      const locked = s.id > p.unlockedStage, done = p.completedStages.includes(s.id);
      this.panel(ctx, bx, by, bw, rowH, done ? '#789b88' : locked ? '#39474b' : '#bf9468');
      ctx.fillStyle = locked ? C.textMuted : C.text; ctx.textAlign = 'left'; ctx.font = `bold ${narrow ? 12 : 15}px Segoe UI, Arial`;
      ctx.fillText(`${String(s.id).padStart(2, '0')}  ${s.name}`, bx + 12, by + 25, bw - 24);
      ctx.fillStyle = C.textSoft; ctx.font = '11px Segoe UI, Arial';
      ctx.fillText(locked ? 'KHÓA' : done ? 'ĐÃ HOÀN THÀNH' : `ĐÃ MỞ · ${s.reward} tín dụng`, bx + 12, by + Math.min(rowH - 10, 46));
      this.add(bx, by, bw, rowH, '', `stage:${s.id - 1}`, locked);
    });
    if (narrow) { this.add(x + 22, y + h - 95, 100, 28, '01–05', 'page:0', this.stagePage === 0); this.add(x + 130, y + h - 95, 100, 28, '06–10', 'page:1', this.stagePage === 1); }
    this.add(x + 22, y + h - 52, 140, 34, '← CHUẨN BỊ', 'back');
  }

  private briefing(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, narrow: boolean, p: SaveSystem['data']['campaign']): void {
    const s = STAGES[this.selectedStage];
    this.title(ctx, `${String(s.id).padStart(2, '0')} / ${s.name}`, x + 22, y + 80);
    if (h < 570) {
      this.copy(ctx, 'NHIỆM VỤ', s.description, x + 24, y + 116, w - 48);
      this.copy(ctx, 'MỤC TIÊU', s.objectiveLabel, x + 24, y + 190, w - 48);
      this.copy(ctx, 'ĐỐI TƯỢNG', `BOSS: ${s.bossName}`, x + 24, y + 260, w - 48);
      this.add(x + 22, y + h - 52, narrow ? 112 : 150, 34, '← BẢN ĐỒ', 'back');
      this.add(x + w - (narrow ? 165 : 205) - 22, y + h - 52, narrow ? 165 : 205, 34, 'VÀO MÀN NGAY →', 'start');
      return;
    }
    this.copy(ctx, 'NHIỆM VỤ', s.description, x + 24, y + 125, w - 48);
    this.copy(ctx, 'MỤC TIÊU CHÍNH', s.objectiveLabel, x + 24, y + 205, w - 48);
    this.copy(ctx, 'MỤC TIÊU PHỤ', 'Khám phá trạm tiếp tế và giữ máu trước trận boss. Thu thập vật tư trên tuyến.', x + 24, y + 285, w - 48);
    this.copy(ctx, 'ĐỐI TƯỢNG', `${s.mobIds.join(' · ')}  /  BOSS: ${s.bossName}`, x + 24, y + 365, w - 48);
    this.copy(ctx, 'CHIẾN THUẬT', 'Đạn hữu hạn. Đi qua hộp để nhặt tiếp tế; E để dùng thiết bị nhiệm vụ; R để thay đạn; Shift/Space để né. Súng P-9 có đạn dự trữ vô hạn.', x + 24, y + Math.min(445, h - 170), w - 48);
    this.add(x + 22, y + h - 52, narrow ? 112 : 150, 34, '← BẢN ĐỒ', 'back');
    this.add(x + w - (narrow ? 165 : 205) - 22, y + h - 52, narrow ? 165 : 205, 34, 'VÀO MÀN NGAY →', 'start');
  }

  private armory(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, p: SaveSystem['data']['campaign'], narrow: boolean): void {
    this.title(ctx, 'TRẠM CHUẨN BỊ', x + 22, y + 77);
    const tabW = (w - 54) / 2;
    this.add(x + 22, y + 87, tabW, 31, 'VŨ KHÍ', 'tab:guns', this.armoryTab === 'guns');
    this.add(x + 32 + tabW, y + 87, tabW, 31, 'DRONE HỘ VỆ', 'tab:drone', this.armoryTab === 'drone');
    if (this.armoryTab === 'guns') this.drawGuns(ctx, x, y, w, h, p, narrow);
    else this.drawDrone(ctx, x, y, w, h, p, narrow);
    this.add(x + 22, y + h - 52, narrow ? 105 : 145, 34, '← NHÂN VẬT', 'back');
    this.add(x + w - (narrow ? 155 : 195) - 22, y + h - 52, narrow ? 155 : 195, 34, 'CHỌN MÀN →', 'stages');
  }

  private drawGuns(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, p: SaveSystem['data']['campaign'], narrow: boolean): void {
    const cols = narrow ? 1 : 2;
    // Keep enough vertical room for readable text and action buttons. Older
    // layouts squeezed all ten guns into five short rows, clipping the status.
    const rows = h < 450 ? 1 : h < 560 ? 2 : h < 680 ? 3 : 4;
    const pageSize = cols * rows, pageCount = Math.ceil(GUNS.length / pageSize);
    this.gunPage = Math.max(0, Math.min(pageCount - 1, this.gunPage));
    const shown = GUNS.slice(this.gunPage * pageSize, (this.gunPage + 1) * pageSize);
    const gap = 7, bw = (w - 44 - gap * (cols - 1)) / cols;
    const rowH = Math.max(64, Math.min(110, (h - 300) / rows - gap));
    shown.forEach((g, i) => {
      const bx = x + 22 + (i % cols) * (bw + gap), by = y + 128 + Math.floor(i / cols) * (rowH + gap);
      const sidearm = g.id === 'p9', owned = sidearm || p.ownedGuns.includes(g.id), level = p.gunLevels[g.id] ?? 0;
      const compact = rowH < 82;
      this.panel(ctx, bx, by, bw, rowH, p.equippedGun === g.id ? C.amberBright : C.borderSoft);
      if (!owned) { ctx.fillStyle = 'rgba(3, 8, 10, .52)'; ctx.fillRect(bx + 1, by + 1, bw - 2, rowH - 2); }
      const artW = narrow ? Math.min(115, bw * .32) : Math.min(175, bw * .38);
      ctx.save(); ctx.globalAlpha = owned ? 1 : .38;
      drawGunArt(ctx, bx + 9, by + 7, artW, Math.min(52, rowH * .48), g.id);
      ctx.restore();
      const tx = bx + artW + 17;
      ctx.fillStyle = owned ? C.text : C.textMuted; ctx.textAlign = 'left'; ctx.font = `bold ${narrow ? 12 : 16}px Segoe UI, Arial`;
      ctx.fillText(`${g.shortName}  ·  ${sidearm ? 'SÚNG LỤC' : g.type.toUpperCase()}`, tx, by + (compact ? 18 : 21), bw - artW - 26);
      ctx.fillStyle = owned ? C.textSoft : C.textMuted; ctx.font = `${narrow ? 9 : 11}px Segoe UI, Arial`;
      ctx.fillText(`${g.baseDamage}${g.pellets ? `×${g.pellets}` : ''} DMG · ${g.rpm} RPM · ${g.magSize} VIÊN`, tx, by + (compact ? 34 : 40), bw - artW - 26);
      const buttonY = by + rowH - (compact ? 23 : 28), buttonH = compact ? 18 : 22, actionW = Math.min(200, (bw - 28) / 2);
      const actionLabel = !owned ? `HẠ BOSS MÀN ${(g.unlockStage ?? 2) - 1} · NHẶT` : p.equippedGun === g.id ? 'ĐANG DÙNG' : 'TRANG BỊ';
      const upgradeCost = 75 * (level + 1);
      const upgradeLabel = sidearm ? 'SÚNG CƠ BẢN' : !owned ? 'CHƯA NHẶT' : level >= 3 ? 'CẤP TỐI ĐA' : p.credits < upgradeCost ? `THIẾU ${upgradeCost} · ${level}/3` : `NÂNG ${upgradeCost} · ${level}/3`;
      this.add(bx + 9, buttonY, actionW, buttonH, actionLabel, `gun:${g.id}`, !owned || p.equippedGun === g.id);
      this.add(bx + 18 + actionW, buttonY, actionW, buttonH, upgradeLabel, `upgrade:${g.id}`, sidearm || !owned || level >= 3 || p.credits < upgradeCost);
    });
    if (pageCount > 1) {
      const pagerY = y + h - 91;
      const pageButtonW = Math.min(100, (w - 100) / 2);
      this.add(x + 22, pagerY, pageButtonW, 25, '← TRƯỚC', `gunpage:${this.gunPage - 1}`, this.gunPage === 0);
      ctx.fillStyle = C.textSoft; ctx.textAlign = 'center'; ctx.font = '12px Segoe UI, Arial'; ctx.fillText(`${this.gunPage + 1}/${pageCount}`, x + w / 2, pagerY + 17);
      this.add(x + w - pageButtonW - 22, pagerY, pageButtonW, 25, 'SAU →', `gunpage:${this.gunPage + 1}`, this.gunPage === pageCount - 1);
    }
    // Anchor supplies below the current page, leaving the pager and footer
    // reserved even when the window is short.
    const supplyY = y + h - 147;
    this.add(x + 22, supplyY, (w - 54) / 2, 27, `ĐẠN +2 BĂNG · 30 (${p.ammoPacks})`, 'ammo', p.ammoPacks >= 4 || p.credits < 30);
    this.add(x + 32 + (w - 54) / 2, supplyY, (w - 54) / 2, 27, `TÚI Y TẾ · 45 (${p.medKits})`, 'med', p.medKits >= 3 || p.credits < 45);
  }

  private dronePrice(level: number): number { return 115 + level * 65; }

  private drawDrone(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number,
    p: SaveSystem['data']['campaign'], narrow: boolean): void {
    const level = Math.min(DRONE_UPGRADE.maxLevel, p.cardLevels.drone ?? 0);
    const maxed = level >= DRONE_UPGRADE.maxLevel;
    const cost = this.dronePrice(level);
    const panelX = x + 22, panelY = y + 128, panelW = w - 44, panelH = h - 235;
    this.panel(ctx, panelX, panelY, panelW, panelH, C.cyanBright);
    ctx.textAlign = 'center'; ctx.fillStyle = C.cyanBright;
    ctx.font = `bold ${narrow ? 12 : 15}px Segoe UI, Arial`;
    ctx.fillText('HỖ TRỢ HỎA LỰC TỰ ĐỘNG', x + w / 2, panelY + 25);
    ctx.font = `${narrow ? 34 : 48}px Segoe UI Emoji, sans-serif`;
    ctx.fillText(DRONE_UPGRADE.icon, x + w / 2, panelY + Math.min(96, panelH * .38));
    ctx.fillStyle = C.text; ctx.font = `bold ${narrow ? 16 : 20}px Segoe UI, Arial`;
    ctx.fillText(DRONE_UPGRADE.name.toUpperCase(), x + w / 2, panelY + Math.min(124, panelH * .51));
    ctx.fillStyle = C.textSoft; ctx.font = `${narrow ? 11 : 13}px Segoe UI, Arial`;
    this.wrap(ctx, 'Drone bay quanh nhân vật và tự động bắn mục tiêu gần nhất. Mỗi cấp thêm một drone.',
      x + 40, panelY + Math.min(151, panelH * .62), w - 80, 17, 2);
    const pipGap = 20, pipStart = x + w / 2 - (DRONE_UPGRADE.maxLevel - 1) * pipGap / 2;
    for (let i = 0; i < DRONE_UPGRADE.maxLevel; i++) {
      ctx.beginPath(); ctx.arc(pipStart + i * pipGap, panelY + panelH - 58, 6, 0, Math.PI * 2);
      ctx.fillStyle = i < level ? C.cyanBright : C.borderSoft; ctx.fill();
    }
    ctx.fillStyle = C.textSoft; ctx.font = 'bold 11px Segoe UI, Arial';
    ctx.fillText(`CẤP ${level}/${DRONE_UPGRADE.maxLevel}  ·  ${level} DRONE ĐANG HOẠT ĐỘNG`, x + w / 2, panelY + panelH - 38);
    const label = maxed ? 'ĐÃ ĐẠT CẤP TỐI ĐA' : `NÂNG DRONE LÊN CẤP ${level + 1}  ·  ${cost} TÍN DỤNG`;
    this.add(x + 42, y + h - 88, w - 84, 32, label, 'drone', maxed || p.credits < cost);
    if (!maxed && p.credits < cost) {
      ctx.fillStyle = C.textMuted; ctx.font = '11px Segoe UI, Arial';
      ctx.fillText(`CÒN THIẾU ${cost - p.credits} TÍN DỤNG`, x + w / 2, y + h - 97);
    }
  }

  private results(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number): void {
    const s = STAGES[this.selectedStage];
    this.title(ctx, `HOÀN THÀNH · ${s.name}`, x + 22, y + 82);
    const rows = [`Thời gian: ${Math.floor(this.result.time / 60)}:${String(Math.floor(this.result.time % 60)).padStart(2, '0')}`,
      `Quái hạ: ${this.result.kills}`, `Mục tiêu chính: hoàn thành`, `Boss: ${s.bossName} đã bị hạ`,
      `Điểm tiếp tế tìm thấy: ${this.result.optional}`, `Thưởng lần đầu: +${this.result.reward} tín dụng`,
      this.result.newStage ? `ĐÃ MỞ MÀN ${this.result.newStage}` : 'Không có màn mới'];
    ctx.textAlign = 'left'; ctx.font = '15px Segoe UI, Arial';
    rows.forEach((line, i) => { ctx.fillStyle = i === 5 ? C.amberBright : C.textSoft; ctx.fillText(line, x + 26, y + 125 + i * Math.min(49, (h - 225) / 7), w - 50); });
    if (w < 600) {
      this.add(x + 22, y + h - 96, w - 44, 34, 'KHO VŨ KHÍ + DRONE', 'post_stage_armory');
      const bw = (w - 52) / 2;
      this.add(x + 22, y + h - 54, bw, 34, 'BẢN ĐỒ', 'stages');
      this.add(x + w - bw - 22, y + h - 54, bw, 34, 'CHƠI LẠI', 'retry');
    } else {
      const bw = Math.min(220, (w - 64) / 3);
      this.add(x + 22, y + h - 54, bw, 36, 'BẢN ĐỒ', 'stages');
      this.add(x + (w - bw) / 2, y + h - 54, bw, 36, 'CHƠI LẠI', 'retry');
      this.add(x + w - bw - 22, y + h - 54, bw, 36, 'KHO VŨ KHÍ + DRONE', 'post_stage_armory');
    }
  }

  private failure(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number): void {
    this.title(ctx, 'NHIỆM VỤ THẤT BẠI', x + 22, y + 82);
    this.copy(ctx, 'BÁO CÁO', `${STAGES[this.selectedStage].name} · ${this.result.kills} quái hạ · ${Math.floor(this.result.time)} giây sống sót`, x + 24, y + 130, w - 48);
    this.copy(ctx, 'TIẾN TRÌNH', 'Không ghi hoàn thành. Súng, drone và tín dụng đã sở hữu vẫn được giữ. Đạn mua trước trận đã dùng cho lượt này.', x + 24, y + 215, w - 48);
    const bw = Math.min(210, (w - 60) / 2);
    this.add(x + 22, y + h - 54, bw, 36, 'KHO VŨ KHÍ', 'return_armory');
    this.add(x + w - bw - 22, y + h - 54, bw, 36, 'THỬ LẠI', 'retry');
  }

  private title(ctx: CanvasRenderingContext2D, text: string, x: number, y: number): void { ctx.textAlign = 'left'; ctx.fillStyle = C.text; ctx.font = 'bold 22px Segoe UI, Arial'; ctx.fillText(text, x, y); }
  private copy(ctx: CanvasRenderingContext2D, label: string, body: string, x: number, y: number, width: number): void {
    ctx.textAlign = 'left'; ctx.fillStyle = C.amberBright; ctx.font = 'bold 12px Segoe UI, Arial'; ctx.fillText(label, x, y);
    ctx.fillStyle = C.textSoft; ctx.font = '13px Segoe UI, Arial'; this.wrap(ctx, body, x, y + 23, width, 18, 2);
  }
  private wrap(ctx: CanvasRenderingContext2D, str: string, x: number, y: number, width: number, lineH: number, maxLines: number): void {
    const words = str.split(' '); let line = '', lines = 0;
    for (const word of words) {
      const next = line ? `${line} ${word}` : word;
      if (ctx.measureText(next).width > width && line) { ctx.fillText(line, x, y + lines * lineH); lines++; line = word; if (lines >= maxLines) return; }
      else line = next;
    }
    if (lines < maxLines) ctx.fillText(line, x, y + lines * lineH);
  }
  private panel(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, stroke: string): void {
    ctx.fillStyle = C.panelRaised; ctx.fillRect(x, y, w, h); ctx.strokeStyle = stroke; ctx.lineWidth = 1.5; ctx.strokeRect(x, y, w, h);
  }
  private add(x: number, y: number, w: number, h: number, label: string, action: string, disabled = false): void { this.buttons.push({ x, y, w, h, label, action, disabled }); }
  private drawButton(ctx: CanvasRenderingContext2D, b: Button): void {
    if (!b.label) return;
    const selected = b.disabled && (b.action.startsWith('tab:') || b.label === 'ĐANG CHỌN' || b.label === 'ĐANG DÙNG');
    ctx.fillStyle = selected ? C.selected : b.disabled ? '#30383c' : '#49675c'; ctx.fillRect(b.x, b.y, b.w, b.h);
    ctx.strokeStyle = selected ? C.selectedBorder : b.disabled ? C.borderSoft : C.health; ctx.strokeRect(b.x, b.y, b.w, b.h);
    ctx.fillStyle = b.disabled && !selected ? C.textMuted : C.text; ctx.textAlign = 'center'; ctx.textBaseline = 'middle';
    ctx.font = `bold ${b.w < 140 ? 10 : 12}px Segoe UI, Arial`; ctx.fillText(b.label, b.x + b.w / 2, b.y + b.h / 2, b.w - 8); ctx.textBaseline = 'alphabetic';
  }
}
