/** Shared anatomical shapes, authored in a 20-unit body radius. */
export const FLESH = { ink: '#1b1b20', skin: '#949580', bone: '#c9bda0', bruise: '#514453', meat: '#703841', cut: '#34222c', wet: '#b47a70' };
const paths = new Map<string, Path2D>();
export function anatomy(path: string): Path2D {
  let cached = paths.get(path);
  if (!cached) { cached = new Path2D(path); paths.set(path, cached); }
  return cached;
}

let texture: HTMLCanvasElement | undefined;
/** One stable texture, never regenerated by animation or hit flashes. */
export function skinGrain(ctx: CanvasRenderingContext2D, shape = ''): void {
  if (!texture) {
    texture = document.createElement('canvas'); texture.width = texture.height = 80;
    const t = texture.getContext('2d')!;
    // Mottled bruising and uneven pallor make the skin read as damaged tissue
    // instead of a clean flat fill. This is rasterized only once.
    const stainSpecs = [
      [12, 18, 10, 6, 'rgba(50,31,49,0.27)'], [53, 13, 12, 5, 'rgba(54,34,45,0.21)'],
      [35, 47, 13, 7, 'rgba(45,31,43,0.19)'], [65, 57, 9, 5, 'rgba(55,32,42,0.23)'],
      [22, 68, 12, 5, 'rgba(183,167,137,0.13)'], [57, 34, 9, 5, 'rgba(180,158,140,0.1)'],
    ] as const;
    for (const [x, y, rx, ry, color] of stainSpecs) {
      t.fillStyle = color; t.beginPath(); t.ellipse(x, y, rx, ry, 0.3, 0, Math.PI * 2); t.fill();
    }
    for (let i = 0; i < 115; i++) {
      const x = (i * 37 + 7) % 80, y = (i * 23 + 17) % 80;
      t.fillStyle = i % 3 ? 'rgba(27,18,26,0.21)' : 'rgba(221,202,164,0.15)';
      t.fillRect(x, y, i % 5 === 0 ? 3 : 0.65, i % 5 === 0 ? 1.1 : 0.7);
    }
    t.strokeStyle = 'rgba(51,24,36,0.48)'; t.lineWidth = 1.1;
    t.beginPath(); t.moveTo(20, 21); t.lineTo(35, 37); t.lineTo(31, 47);
    t.moveTo(35, 37); t.lineTo(47, 43); t.lineTo(49, 53); t.stroke();
  }
  let hash = 0;
  for (let i = 0; i < shape.length; i++) hash = (hash * 31 + shape.charCodeAt(i)) | 0;
  ctx.drawImage(texture, -40 + (hash & 15), -40 + ((hash >>> 4) & 15));
}

export function tissue(ctx: CanvasRenderingContext2D, shape: string, color: string, flash = false): void {
  const p = anatomy(shape);
  ctx.fillStyle = flash ? '#d3c4ad' : color; ctx.fill(p);
  ctx.strokeStyle = FLESH.ink; ctx.lineWidth = 0.85; ctx.stroke(p);
  ctx.save(); ctx.clip(p);
  ctx.fillStyle = 'rgba(20,17,25,0.18)';
  ctx.fill(anatomy('M-25 3 Q-11 5 -2 2 Q11 0 24 7 L28 27 L-26 29 Z'));
  if (!flash) skinGrain(ctx, shape);
  ctx.restore();
}

export function wound(ctx: CanvasRenderingContext2D, x: number, y: number, scale = 1, angle = 0, ribs = false): void {
  ctx.save(); ctx.translate(x, y); ctx.rotate(angle); ctx.scale(scale, scale);
  ctx.fillStyle = FLESH.meat;
  ctx.fill(anatomy('M-7 -5 L-3 -7 L-1 -5 L4 -6 L7 -2 L5 1 L7 5 L1 7 L-4 5 L-7 6 L-5 1 Z'));
  ctx.fillStyle = FLESH.cut;
  ctx.fill(anatomy('M-4 -4 L0 -3 L4 -4 L4 1 L2 5 L-4 3 L-3 0 Z'));
  ctx.strokeStyle = ribs ? FLESH.bone : FLESH.wet; ctx.lineWidth = ribs ? 1.1 : 0.7;
  ctx.beginPath();
  for (let i = 0; i < 4; i++) {
    const py = -4 + i * 2.4;
    ctx.moveTo(-5, py); ctx.quadraticCurveTo(-1, py + 2, 3.5 - i * 0.5, py + 0.5);
  }
  ctx.stroke();
  ctx.strokeStyle = '#c0a28d'; ctx.lineWidth = 0.55;
  ctx.beginPath(); ctx.moveTo(-6, -5); ctx.lineTo(-3, -6); ctx.moveTo(5, 2); ctx.lineTo(4, 5); ctx.stroke();
  ctx.restore();
}

export function brokenHead(ctx: CanvasRenderingContext2D, x: number, y: number, angle: number, scale: number, color: string, flash: boolean, gape: number): void {
  ctx.save(); ctx.translate(x, y); ctx.rotate(angle); ctx.scale(scale, scale);
  tissue(ctx, 'M-7 -3 Q-7 -8 -1 -7 L3 -6 L4 -3 L7 -1 L4 1 L5 4 L1 5 L-4 4 L-6 1 Z', color, flash);
  ctx.fillStyle = flash ? '#e4d7bd' : '#b2b09b';
  ctx.fill(anatomy('M-6 -3 Q-5 -7 -1 -6 L1 -5 L-1 -2 L-4 0 Z'));
  ctx.fillStyle = '#24212a';
  ctx.fill(anatomy('M0 -4 L4 -3 L3 -1 L0 -1 Z M-1 2 L2 1 L3 3 L0 4 Z'));
  ctx.strokeStyle = '#51434a'; ctx.lineWidth = 0.75;
  ctx.beginPath(); ctx.moveTo(-4, -5); ctx.lineTo(-2, -3); ctx.lineTo(-3, 0); ctx.stroke();
  ctx.save(); ctx.translate(3, 1); ctx.rotate(0.22 + gape * 0.12);
  ctx.fillStyle = FLESH.cut;
  ctx.beginPath(); ctx.moveTo(0, -2); ctx.lineTo(5, -1); ctx.lineTo(6, 3 + gape); ctx.lineTo(0, 4 + gape); ctx.closePath(); ctx.fill();
  ctx.strokeStyle = flash ? '#dbcfb7' : FLESH.wet; ctx.lineWidth = 1;
  ctx.beginPath(); ctx.moveTo(-1, 0); ctx.lineTo(0, 4 + gape); ctx.lineTo(5, 3 + gape); ctx.stroke();
  ctx.fillStyle = FLESH.bone;
  ctx.beginPath(); ctx.moveTo(1, -1); ctx.lineTo(2.1, 1.5); ctx.lineTo(2.5, -1);
  ctx.moveTo(3, -0.5); ctx.lineTo(4.3, 1.2); ctx.lineTo(4.5, -0.5);
  ctx.moveTo(2, 3 + gape); ctx.lineTo(2.8, 1.2 + gape); ctx.lineTo(3.5, 3 + gape); ctx.fill();
  ctx.strokeStyle = '#94685d'; ctx.lineWidth = 0.5;
  ctx.beginPath(); ctx.moveTo(4, 0); ctx.lineTo(5, 3 + gape); ctx.stroke();
  ctx.restore(); ctx.restore();
}

export function sinew(ctx: CanvasRenderingContext2D, ax: number, ay: number, bx: number, by: number, cx: number, cy: number, width: number, color: string, flash: boolean): void {
  ctx.lineJoin = 'round'; ctx.lineCap = 'round';
  ctx.beginPath(); ctx.moveTo(ax, ay); ctx.lineTo(bx, by); ctx.lineTo(cx, cy);
  ctx.strokeStyle = FLESH.ink; ctx.lineWidth = width + 1.3; ctx.stroke();
  ctx.strokeStyle = flash ? '#d5c6b1' : color; ctx.lineWidth = width; ctx.stroke();
  ctx.strokeStyle = flash ? '#eee3c8' : '#b7ad95'; ctx.lineWidth = Math.max(0.55, width * 0.17);
  ctx.beginPath(); ctx.moveTo(ax, ay - width * 0.2); ctx.lineTo(bx - 1, by - 0.8); ctx.lineTo(cx - 1, cy); ctx.stroke();
  ctx.strokeStyle = '#613b45'; ctx.lineWidth = Math.max(0.6, width * 0.2);
  ctx.beginPath(); ctx.moveTo(bx - width * 0.3, by - 1); ctx.lineTo(bx + width * 0.3, by + 1); ctx.stroke();
}

export function fingers(ctx: CanvasRenderingContext2D, x: number, y: number, angle: number, length: number): void {
  ctx.save(); ctx.translate(x, y); ctx.rotate(angle);
  ctx.lineCap = 'round'; ctx.strokeStyle = '#a8a58d'; ctx.lineWidth = 1;
  ctx.beginPath();
  for (let i = 0; i < 3; i++) {
    ctx.moveTo(0, i * 1.7 - 2); ctx.lineTo(length * (0.55 + i * 0.08), i * 2 - 2.5); ctx.lineTo(length - i * 0.7, i * 2.1 - 0.5);
  }
  ctx.stroke(); ctx.restore();
}
